const http = require('http');

function createProblem(question, answer, categorySN) {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify({ question, answer, category: categorySN, hit: '0' });
    const req = http.request({
      hostname: '192.168.0.3', port: 8080, path: '/problem', method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) }
    }, res => { let b = ''; res.on('data', d => b += d); res.on('end', () => resolve(b)); });
    req.on('error', reject);
    req.write(data); req.end();
  });
}

// Additional terms for categories 2-6 (original CS subjects)
const extraTerms = {
  2: [ // 컴퓨터 구조 - extra
    ["폰 노이만 아키텍처", "CPU와 메모리가 하나의 버스로 연결된 컴퓨터 구조"],
    ["하버드 아키텍처", "명령어와 데이터 버스가 분리된 컴퓨터 구조"],
    ["수직 마이크로코드", "비트 필드로 구성된 마이크로코드 방식"],
    ["수평 마이크로코드", "각 비트가 직접 제어 신호를 나타내는 마이크로코드 방식"],
    ["마이크로 연산", "CPU 클럭 한 주기에 실행되는 가장 기본적인 연산"],
    ["명령어 파이프라인 해저드", "파이프라인에서 명령어 실행을 방해하는 요소"],
    ["RAW 해저드", "읽기 후 쓰기 의존성으로 인한 데이터 해저드"],
    ["WAR 해저드", "쓰기 후 읽기 의존성으로 인한 데이터 해저드"],
    ["WAW 해저드", "쓰기 후 쓰기 의존성으로 인한 데이터 해저드"],
    ["분기 예측 오류", "분기 예측이 실패하여 파이프라인이 플러시되는 현상"],
    ["2단계 분기 예측", "분기 이력을 2비트로 기록하는 분기 예측 기법"],
    ["BTB(Branch Target Buffer)", "분기 목적지 주소를 저장하는 버퍼"],
    ["비순차적 완료", "명령어가 순서와 상관없이 완료되는 현상"],
    ["재순서 버퍼(ROB)", "비순차적 실행 결과를 순서대로 다시 정렬하는 버퍼"],
    ["레지스터 리네이밍", "레지스터 이름을 바꾸어 데이터 의존성을 제거하는 기법"],
    ["명령어 이슈", "디코딩된 명령어를 실행 유닛에 전달하는 과정"],
    ["VLIW(Very Long Instruction Word)", "하나의 명령어에 여러 연산을 포함하는 기술"],
    ["EPIC(Explicitly Parallel Instruction Computing)", "명시적 병렬 명령어 컴퓨팅"],
    ["SIMD(Single Instruction Multiple Data)", "하나의 명령어로 여러 데이터를 처리하는 방식"],
    ["MIMD(Multiple Instruction Multiple Data)", "여러 명령어로 여러 데이터를 처리하는 방식"],
    ["SISD(Single Instruction Single Data)", "하나의 명령어로 하나의 데이터를 처리하는 방식"],
    ["벡터 프로세서", "벡터 연산을 효율적으로 처리하는 프로세서"],
    ["FPGA(Field-Programmable Gate Array)", "프로그래밍 가능한 반도체 칩"],
    ["ASIC(Application-Specific Integrated Circuit)", "특정 용도로 설계된 집적 회로"],
    ["SoC(System on a Chip)", "하나의 칩에 여러 시스템 구성 요소를 통합한 것"],
    ["ECC 메모리(Error-Correcting Code Memory)", "오류를 검출하고 수정할 수 있는 메모리"],
    ["메모리 인터리빙", "메모리를 여러 뱅크로 나누어 동시 접근을 가능하게 하는 기술"],
    ["듀얼 채널 메모리", "두 개의 메모리 채널을 사용하여 대역폭을 두 배로 늘리는 기술"],
    ["캐시 일관성(Cache Coherency)", "여러 캐시의 데이터 일관성을 유지하는 문제"],
    ["MESI 프로토콜", "Modified, Exclusive, Shared, Invalid 상태로 캐시 일관성을 유지하는 프로토콜"],
    ["디렉토리 기반 일관성", "디렉토리를 사용하는 캐시 일관성 프로토콜"],
    ["스누핑(Snooping)", "버스를 모니터링하는 캐시 일관성 프로토콜"],
    ["NUMA(Non-Uniform Memory Access)", "메모리 접근 시간이 균일하지 않은 아키텍처"],
    ["UMA(Uniform Memory Access)", "모든 메모리 접근 시간이 동일한 아키텍처"],
    ["CC-NUMA(Cache-Coherent NUMA)", "캐시 일관성을 지원하는 NUMA"],
    ["PCI Express(PCIe)", "고속 직렬 입출력 버스 표준"],
    ["인터럽트 컨트롤러", "인터럽트를 관리하는 하드웨어"],
    ["APIC(Advanced Programmable Interrupt Controller)", "고급 프로그래머블 인터럽트 컨트롤러"],
    ["DMA(Direct Memory Access)", "CPU를 거치지 않고 메모리와 입출력 장치 간 데이터 전송"],
    ["Bus Mastering", "버스 마스터가 버스 제어권을 가지고 데이터를 전송하는 방식"],
    ["메모리 맵 입출력(MMIO)", "메모리 주소 공간에 입출력 장치를 매핑하는 방식"],
    ["고립형 입출력(Isolated I/O)", "입출력 전용 주소 공간을 사용하는 방식"],
    ["플러그 앤 플레이(PnP)", "장치를 자동으로 인식하고 설정하는 기술"],
    ["ACPI(Advanced Configuration and Power Interface)", "전원 관리 인터페이스 표준"],
    ["UEFI(Unified Extensible Firmware Interface)", "기존 BIOS를 대체하는 펌웨어 인터페이스"],
    ["부트로더(Bootloader)", "운영체제를 메모리에 로드하는 프로그램"],
    ["MBR(Master Boot Record)", "전통적인 부트 섹터 방식"],
    ["GPT(GUID Partition Table)", "UEFI에서 사용하는 파티션 테이블"],
    ["RAID(Redundant Array of Independent Disks)", "여러 디스크를 하나처럼 사용하는 기술"],
    ["JBOD(Just a Bunch Of Disks)", "여러 디스크를 단순히 묶어 사용하는 방식"],
    ["SATA(Serial ATA)", "직렬 방식의 ATA 인터페이스"],
    ["NVMe(Non-Volatile Memory Express)", "SSD를 위한 고속 인터페이스 프로토콜"],
    ["AHCI(Advanced Host Controller Interface)", "SATA 컨트롤러를 위한 인터페이스"],
    ["NAND 플래시 메모리", "비휘발성 저장 장치의 한 종류"],
    ["셀 레벨(SLC/MLC/TLC/QLC)", "플래시 메모리 셀당 저장 비트 수에 따른 분류"],
    ["웨어 레벨링(Wear Leveling)", "플래시 메모리의 수명을 균등하게 하는 기술"],
    ["TRIM 명령", "SSD에서 불필요한 데이터 블록을 미리 정리하는 명령"],
    ["OP(Over-Provisioning)", "SSD 성능 최적화를 위한 여유 공간"],
    ["NVMe over Fabrics", "네트워크를 통한 NVMe 프로토콜"],
    ["SMR(Shingled Magnetic Recording)", "하드 디스크의 기록 밀도를 높이는 기술"],
    ["HAMR(Heat-Assisted Magnetic Recording)", "열을 이용한 자기 기록 기술"],
    ["캐시 태그 배열", "캐시 메모리의 태그 정보를 저장하는 배열"],
    ["직접 매핑(Direct Mapping)", "각 메모리 블록이 특정 캐시 라인에만 매핑되는 방식"],
    ["완전 연관 매핑(Fully Associative)", "메모리 블록이 모든 캐시 라인에 매핑될 수 있는 방식"],
    ["세트 연관 매핑(Set Associative)", "직접 매핑과 완전 연관 매핑의 절충 방식"],
    ["캐시 라인", "캐시 메모리의 최소 저장 단위"],
    ["미스율(Miss Rate)", "캐시 미스가 발생하는 비율"],
    ["미스 패널티(Miss Penalty)", "캐시 미스 발생 시 추가로 소요되는 시간"],
    ["3C 모델", "캐시 미스의 세 가지 원인(Compulsory, Capacity, Conflict)"],
    ["강제 미스(Compulsory Miss)", "데이터가 처음 접근되어 발생하는 캐시 미스"],
    ["용량 미스(Capacity Miss)", "캐시 크기가 부족하여 발생하는 캐시 미스"],
    ["충돌 미스(Conflict Miss)", "매핑 제약으로 인해 발생하는 캐시 미스"],
    ["프리페치(Prefetching)", "데이터를 미리 가져오는 캐시 최적화 기법"],
    ["하드웨어 프리페처", "하드웨어에서 자동으로 수행하는 프리페치"],
    ["소프트웨어 프리페치", "컴파일러가 삽입한 프리페치 명령어"],
  ],
  3: [ // 운영체제 - extra
    ["스핀락(Spinlock)", "루프를 돌며 락을 기다리는 동기화 방식"],
    ["RWLock(Read-Write Lock)", "읽기는 동시에, 쓰기는 배타적으로 허용하는 락"],
    ["배리어(Barrier)", "모든 스레드가 도착할 때까지 기다리는 동기화 기법"],
    ["원자적 연산(Atomic Operation)", "중단 없이 한 번에 실행되는 연산"],
    ["CAS(Compare-And-Swap)", "값을 비교하고 교체하는 원자적 연산"],
    ["ABA 문제", "CAS 사용 시 값이 A->B->A로 변경되어 문제가 발생하는 현상"],
    ["락 프리(데이터 구조 Lock-Free)", "락 없이 동시성을 보장하는 데이터 구조"],
    ["Wait-Free", "모든 스레드가 유한한 단계 내에 완료됨을 보장하는 기법"],
    ["페어 락(Fair Lock)", "스레드가 락을 획득하는 순서를 보장하는 락"],
    ["락 프리(프로그래밍)", "데드락 없이 동시성을 보장하는 프로그래밍 기법"],
    ["CPU 선호도(CPU Affinity)", "프로세스나 스레드를 특정 CPU에 고정하는 것"],
    ["빅(Big) 코어 / 리틀(Little) 코어", "고성능 코어와 고효율 코어를 혼합한 CPU 아키텍처"],
    ["CPUID 명령어", "CPU의 기능과 정보를 조회하는 명령어"],
    ["하이퍼바이저(Hypervisor)", "가상 머신을 관리하는 소프트웨어"],
    ["타입 1 하이퍼바이저", "하드웨어 위에서 직접 실행되는 하이퍼바이저"],
    ["타입 2 하이퍼바이저", "호스트 OS 위에서 실행되는 하이퍼바이저"],
    ["전가상화(Full Virtualization)", "하드웨어를 완전히 가상화하는 방식"],
    ["반가상화(Para-virtualization)", "게스트 OS가 수정되어 가상화를 인지하는 방식"],
    ["KVM(Kernel-based Virtual Machine)", "리눅스 커널 기반 가상화 기술"],
    ["Xen", "널리 사용되는 오픈소스 하이퍼바이저"],
    ["도커(Docker)", "컨테이너 기반 가상화 플랫폼"],
    ["cgroups", "리눅스 커널의 프로세스 자원 제어 기능"],
    ["네임스페이스(Namespace)", "리눅스 커널의 리소스 격리 기능"],
    ["AUFS(Another Union File System)", "도커에서 사용하는 유니온 파일 시스템"],
    ["오버레이 파일 시스템(OverlayFS)", "도커에서 사용하는 또 다른 유니온 파일 시스템"],
    ["리눅스 컨테이너(LXC)", "리눅스 컨테이너 기술"],
    ["runC", "OCI 표준을 따르는 컨테이너 런타임"],
    ["containerd", "산업 표준 컨테이너 런타임"],
    ["CRI-O", "Kubernetes CRI를 위한 컨테이너 런타임"],
    ["도커 이미지", "컨테이너 실행에 필요한 모든 파일을 포함한 패키지"],
    ["도커 레지스트리", "도커 이미지를 저장하고 배포하는 서버"],
    ["도커 허브(Docker Hub)", "공식 도커 이미지 레지스트리"],
    ["도커파일(Dockerfile)", "도커 이미지 빌드를 위한 설정 파일"],
    ["도커 컴포즈(Docker Compose)", "멀티 컨테이너 도커 애플리케이션 관리 도구"],
    ["쿠버네티스(Kubernetes)", "컨테이너 오케스트레이션 플랫폼"],
    ["포드(Pod)", "쿠버네티스에서 가장 작은 배포 단위"],
    ["서비스(Service)", "쿠버네티스에서 포드 집합에 접근하기 위한 추상화"],
    ["디플로이먼트(Deployment)", "포드의 선언적 업데이트를 관리하는 쿠버네티스 리소스"],
    ["스테이트풀셋(StatefulSet)", "상태가 있는 애플리케이션을 위한 쿠버네티스 리소스"],
    ["데몬셋(DaemonSet)", "모든 노드에 포드를 실행하는 쿠버네티스 리소스"],
    ["컨피그맵(ConfigMap)", "설정 데이터를 저장하는 쿠버네티스 리소스"],
    ["시크릿(Secret)", "민감한 데이터를 저장하는 쿠버네티스 리소스"],
    ["인그레스(Ingress)", "클러스터 외부에서 내부 서비스로의 HTTP 접근을 관리하는 리소스"],
    ["퍼시스턴트 볼륨(PV)", "관리자가 제공하는 스토리지"],
    ["퍼시스턴트 볼륨 클레임(PVC)", "사용자가 요청하는 스토리지"],
    ["Helm", "쿠버네티스 패키지 매니저"],
    ["kubectl", "쿠버네티스 CLI 도구"],
    ["Kubelet", "각 노드에서 실행되는 쿠버네티스 에이전트"],
    ["컨트롤 플레인(Control Plane)", "클러스터의 상태를 관리하는 쿠버네티스 구성 요소"],
    ["kube-apiserver", "쿠버네티스 API를 제공하는 서버"],
    ["etcd", "쿠버네티스의 분산 키-값 저장소"],
    ["kube-scheduler", "포드를 노드에 할당하는 스케줄러"],
    ["kube-controller-manager", "컨트롤러를 관리하는 구성 요소"],
    ["coredns", "쿠버네티스 클러스터의 DNS 서버"],
    ["CNI(Container Network Interface)", "컨테이너 네트워크 인터페이스 표준"],
    ["Calico", "쿠버네티스 네트워크 플러그인"],
    ["Flannel", "간단한 쿠버네티스 네트워크 플러그인"],
    ["서비스 메시(Service Mesh)", "마이크로서비스 간 통신을 관리하는 인프라"],
    ["Istio", "대표적인 서비스 메시 솔루션"],
    ["Envoy Proxy", "Istio의 데이터 플레인 프록시"],
    ["오토스케일링(Auto Scaling)", "자동으로 리소스를 조정하는 기술"],
    ["HPA(Horizontal Pod Autoscaler)", "포드 수를 자동으로 조정하는 쿠버네티스 기능"],
    ["VPA(Vertical Pod Autoscaler)", "포드의 리소스 할당량을 자동으로 조정하는 기능"],
    ["클러스터 오토스케일러", "노드 수를 자동으로 조정하는 기능"],
  ],
  4: [ // 네트워크 - extra
    ["DNS(Domain Name System)", "도메인 이름을 IP 주소로 변환하는 시스템"],
    ["DHCP(Dynamic Host Configuration Protocol)", "IP 주소를 자동으로 할당하는 프로토콜"],
    ["NAT(Network Address Translation)", "사설 IP를 공인 IP로 변환하는 기술"],
    ["PAT(Port Address Translation)", "포트를 이용한 NAT의 한 종류"],
    ["ARP(Address Resolution Protocol)", "IP 주소를 MAC 주소로 변환하는 프로토콜"],
    ["RARP(Reverse ARP)", "MAC 주소를 IP 주소로 변환하는 프로토콜"],
    ["ICMP(Internet Control Message Protocol)", "네트워크 오류 보고 프로토콜"],
    ["IGMP(Internet Group Management Protocol)", "멀티캐스트 그룹 관리 프로토콜"],
    ["멀티캐스트(Multicast)", "하나의 송신자가 여러 수신자에게 데이터를 전송하는 방식"],
    ["브로드캐스트(Broadcast)", "네트워크 내 모든 장치에 데이터를 전송하는 방식"],
    ["유니캐스트(Unicast)", "하나의 송신자가 하나의 수신자에게 데이터를 전송하는 방식"],
    ["애니캐스트(Anycast)", "가장 가까운 수신자에게 데이터를 전송하는 방식"],
    ["게이트웨이(Gateway)", "서로 다른 네트워크를 연결하는 장치"],
    ["리피터(Repeater)", "신호를 증폭하여 전송 거리를 늘리는 장치"],
    ["허브(Hub)", "여러 장치를 연결하는 기본적인 네트워크 장치"],
    ["브리지(Bridge)", "두 네트워크 세그먼트를 연결하는 장치"],
    ["스위치(Switch)", "MAC 주소 기반으로 패킷을 전달하는 장치"],
    ["라우터(Router)", "IP 주소 기반으로 패킷을 전달하는 장치"],
    ["L3 스위치", "라우팅 기능이 있는 스위치"],
    ["방화벽(Firewall)", "네트워크 트래픽을 제어하는 보안 장치"],
    ["프록시 서버(Proxy Server)", "클라이언트를 대신하여 요청을 처리하는 서버"],
    ["리버스 프록시(Reverse Proxy)", "서버를 대신하여 요청을 받는 프록시"],
    ["로드 밸런서(Load Balancer)", "트래픽을 여러 서버로 분산하는 장치"],
    ["VPN(Virtual Private Network)", "가상 사설 네트워크"],
    ["VLAN(Virtual LAN)", "가상 LAN"],
    ["MAC(Media Access Control) 주소", "네트워크 인터페이스의 고유 물리 주소"],
    ["MTU(Maximum Transmission Unit)", "네트워크에서 전송 가능한 최대 패킷 크기"],
    ["MSS(Maximum Segment Size)", "TCP에서 전송 가능한 최대 세그먼트 크기"],
    ["TTL(Time To Live)", "패킷의 최대 수명"],
    ["홉(Hop)", "패킷이 거치는 네트워크 장치"],
    ["레이턴시(Latency)", "네트워크 지연 시간"],
    ["대역폭(Bandwidth)", "네트워크 전송 용량"],
    ["처리량(Throughput)", "실제 전송되는 데이터의 양"],
    ["지터(Jitter)", "패킷 도착 시간의 변동"],
    ["QoS(Quality of Service)", "네트워크 서비스 품질 제어"],
    ["SLA(Service Level Agreement)", "서비스 수준 계약"],
    ["SNMP(Simple Network Management Protocol)", "네트워크 관리 프로토콜"],
    ["NetFlow", "Cisco의 네트워크 트래픽 모니터링 기술"],
    ["sFlow", "샘플링 기반 트래픽 모니터링 기술"],
    ["SDN(Software-Defined Networking)", "소프트웨어로 네트워크를 제어하는 기술"],
    ["NFV(Network Function Virtualization)", "네트워크 기능을 가상화하는 기술"],
    ["OpenFlow", "SDN에서 사용하는 프로토콜"],
    ["VXLAN(Virtual Extensible LAN)", "대규모 가상 네트워크를 위한 터널링 프로토콜"],
    ["GRE(Generic Routing Encapsulation)", "다양한 프로토콜을 캡슐화하는 터널링 프로토콜"],
    ["IPsec(IP Security)", "IP 계층 보안 프로토콜"],
    ["SSL/TLS", "전송 계층 보안 프로토콜"],
    ["DTLS(Datagram TLS)", "UDP를 위한 TLS"],
    ["SSH(Secure Shell)", "암호화된 원격 접속 프로토콜"],
    ["Telnet", "암호화되지 않은 원격 접속 프로토콜"],
    ["FTP(File Transfer Protocol)", "파일 전송 프로토콜"],
    ["SFTP(SSH File Transfer Protocol)", "SSH 기반 파일 전송 프로토콜"],
    ["FTPS(FTP over SSL)", "SSL 기반 FTP"],
    ["SMTP(Simple Mail Transfer Protocol)", "이메일 전송 프로토콜"],
    ["POP3(Post Office Protocol 3)", "이메일 수신 프로토콜"],
    ["IMAP(Internet Message Access Protocol)", "이메일 접근 프로토콜"],
    ["MIME(Multipurpose Internet Mail Extensions)", "이메일 첨부 파일 표준"],
    ["XMPP(Extensible Messaging and Presence Protocol)", "메시징 프로토콜"],
    ["WebSocket", "양방향 통신 프로토콜"],
    ["HTTP/2", "향상된 HTTP 프로토콜"],
    ["HTTP/3", "QUIC 기반 HTTP 프로토콜"],
    ["gRPC(Remote Procedure Call)", "Google의 고성능 RPC 프레임워크"],
    ["REST(Representational State Transfer)", "HTTP 기반 API 설계 스타일"],
    ["SOAP(Simple Object Access Protocol)", "XML 기반 프로토콜"],
    ["GraphQL", "API를 위한 쿼리 언어"],
    ["JSON(JavaScript Object Notation)", "경량 데이터 교환 형식"],
    ["XML(eXtensible Markup Language)", "확장 가능한 마크업 언어"],
    ["YAML(YAML Ain't Markup Language)", "사람이 읽기 쉬운 데이터 직렬화 형식"],
    ["프로토콜 버퍼(Protocol Buffers)", "Google의 효율적인 직렬화 형식"],
    ["아파치(APACHE) 라이선스", "Apache Software Foundation의 오픈소스 라이선스"],
    ["GPL(General Public License)", "GNU 일반 공중 사용 허가서"],
    ["MIT 라이선스", "자유 소프트웨어 라이선스"],
    ["BSD 라이선스", "버클리 소프트웨어 배포 라이선스"],
    ["MPL(Mozilla Public License)", "Mozilla 재단의 오픈소스 라이선스"],
    ["MVC(Model-View-Controller)", "소프트웨어 디자인 패턴"],
    ["MVP(Model-View-Presenter)", "MVC 변형 패턴"],
    ["MVVM(Model-View-ViewModel)", "MVC 변형 패턴"],
    ["Flux 아키텍처", "단방향 데이터 흐름 아키텍처"],
    ["Redux", "Flux 기반 상태 관리 라이브러리"],
    ["리액트(React)", "Facebook의 UI 라이브러리"],
    ["앵귤러(Angular)", "Google의 웹 프레임워크"],
    ["뷰(Vue.js)", "진보적인 자바스크립트 프레임워크"],
    ["Svelte", "컴파일러 기반 웹 프레임워크"],
    ["Node.js", "서버 사이드 자바스크립트 런타임"],
    ["Express.js", "Node.js 웹 프레임워크"],
    ["Django", "Python 웹 프레임워크"],
    ["Spring", "자바 웹 프레임워크"],
    ["Flask", "Python 마이크로 웹 프레임워크"],
  ],
  5: [ // 데이터베이스 - extra
    ["ACID", "트랜잭션의 원자성, 일관성, 고립성, 지속성"],
    ["원자성(Atomicity)", "트랜잭션의 모든 연산이 완전히 수행되거나 전혀 수행되지 않아야 하는 성질"],
    ["일관성(Consistency)", "트랜잭션 수행 후 데이터베이스의 일관성이 유지되는 성질"],
    ["고립성(Isolation)", "트랜잭션이 동시에 수행될 때 서로 영향을 주지 않는 성질"],
    ["지속성(Durability)", "커밋된 트랜잭션의 결과가 영구적으로 저장되는 성질"],
    ["스키마(Schema)", "데이터베이스의 구조와 제약 조건을 정의한 것"],
    ["카디널리티(Cardinality)", "릴레이션 튜플의 개수"],
    ["차수(Degree)", "릴레이션 속성의 개수"],
    ["도메인(Domain)", "속성이 가질 수 있는 값의 집합"],
    ["NULL", "알 수 없는 값을 나타내는 특수한 값"],
    ["JOIN", "두 개 이상의 테이블을 연결하는 연산"],
    ["INNER JOIN", "조인 조건을 만족하는 행만 반환하는 조인"],
    ["LEFT JOIN", "왼쪽 테이블의 모든 행을 포함하는 조인"],
    ["RIGHT JOIN", "오른쪽 테이블의 모든 행을 포함하는 조인"],
    ["FULL OUTER JOIN", "양쪽 테이블의 모든 행을 포함하는 조인"],
    ["CROSS JOIN", "두 테이블의 모든 가능한 조합을 반환하는 조인"],
    ["SELF JOIN", "자기 자신과 조인하는 방식"],
    ["서브쿼리(Subquery)", "쿼리 내에 포함된 또 다른 쿼리"],
    ["상관 서브쿼리(Correlated Subquery)", "외부 쿼리의 값을 참조하는 서브쿼리"],
    ["EXISTS 연산자", "서브쿼리의 결과 존재 여부를 확인하는 연산자"],
    ["IN 연산자", "값이 집합에 포함되는지 확인하는 연산자"],
    ["BETWEEN 연산자", "값의 범위를 확인하는 연산자"],
    ["LIKE 연산자", "패턴 매칭을 수행하는 연산자"],
    ["DISTINCT", "중복된 값을 제거하는 키워드"],
    ["GROUP BY", "특정 컬럼으로 그룹화하는 절"],
    ["HAVING", "그룹에 대한 조건을 지정하는 절"],
    ["ORDER BY", "결과를 정렬하는 절"],
    ["LIMIT", "결과의 개수를 제한하는 절"],
    ["OFFSET", "결과의 시작 위치를 지정하는 절"],
    ["CREATE TABLE", "새로운 테이블을 생성하는 DDL"],
    ["ALTER TABLE", "테이블 구조를 변경하는 DDL"],
    ["DROP TABLE", "테이블을 삭제하는 DDL"],
    ["TRUNCATE TABLE", "테이블의 모든 데이터를 삭제하는 DDL"],
    ["INSERT", "데이터를 삽입하는 DML"],
    ["UPDATE", "데이터를 수정하는 DML"],
    ["DELETE", "데이터를 삭제하는 DML"],
    ["SELECT", "데이터를 조회하는 DML"],
    ["GRANT", "권한을 부여하는 DCL"],
    ["REVOKE", "권한을 회수하는 DCL"],
    ["COMMIT", "트랜잭션을 확정하는 TCL"],
    ["ROLLBACK", "트랜잭션을 취소하는 TCL"],
    ["SAVEPOINT", "트랜잭션 내 저장점을 설정하는 TCL"],
    ["제1정규형(1NF)", "모든 속성이 원자값을 가지는 정규형"],
    ["제2정규형(2NF)", "부분 함수 종속을 제거한 정규형"],
    ["제3정규형(3NF)", "이행적 함수 종속을 제거한 정규형"],
    ["보이스-코드 정규형(BCNF)", "모든 결정자가 후보키인 정규형"],
    ["제4정규형(4NF)", "다치 종속을 제거한 정규형"],
    ["제5정규형(5NF)", "조인 종속을 제거한 정규형"],
    ["함수 종속(Functional Dependency)", "속성 간의 종속 관계"],
    ["완전 함수 종속", "기본키 전체에 종속된 관계"],
    ["부분 함수 종속", "기본키의 일부에 종속된 관계"],
    ["이행적 함수 종속", "간접적인 종속 관계"],
    ["다치 종속(Multivalued Dependency)", "하나의 값이 여러 값에 종속된 관계"],
    ["조인 종속(Join Dependency)", "조인을 통해 복원 가능한 분해 관계"],
    ["NoSQL", "비관계형 데이터베이스"],
    ["MongoDB", "대표적인 문서 기반 NoSQL 데이터베이스"],
    ["Redis", "인메모리 키-값 저장소"],
    ["Cassandra", "분산형 NoSQL 데이터베이스"],
    ["CouchDB", "JSON 문서 기반 NoSQL 데이터베이스"],
    ["HBase", "Hadoop 기반 NoSQL 데이터베이스"],
    ["Neo4j", "그래프 데이터베이스"],
    ["Elasticsearch", "분산 검색 및 분석 엔진"],
    ["InfluxDB", "시계열 데이터베이스"],
    ["CAP 정리(일관성-가용성-분할내성)", "분산 데이터베이스의 세 가지 특성"],
    ["최종 일관성(Eventual Consistency)", "시간이 지나면 일관성이 유지되는 모델"],
    ["강력 일관성(Strong Consistency)", "즉시 일관성이 유지되는 모델"],
    ["결과적 일관성(Consistency)", "CAP 정리에서의 일관성"],
    ["분할 내성(Partition Tolerance)", "네트워크 분할에도 시스템이 작동하는 능력"],
    ["샤딩(Sharding)", "데이터를 여러 노드에 분할 저장하는 기술"],
    ["레플리케이션(Replication)", "데이터를 복제하는 기술"],
    ["레플리카 세트(Replica Set)", "MongoDB의 복제 그룹"],
    ["OLTP(Online Transaction Processing)", "온라인 트랜잭션 처리"],
    ["OLAP(Online Analytical Processing)", "온라인 분석 처리"],
    ["데이터 웨어하우스(Data Warehouse)", "분석을 위한 데이터 저장소"],
    ["데이터 마트(Data Mart)", "특정 주제의 데이터 웨어하우스"],
    ["ETL(Extract, Transform, Load)", "데이터 추출, 변환, 적재 과정"],
    ["빅데이터(Big Data)", "대규모 데이터"],
    ["데이터 마이닝(Data Mining)", "데이터에서 패턴을 발견하는 기술"],
    ["데이터 시각화(Data Visualization)", "데이터를 시각적으로 표현하는 기술"],
    ["물리적 설계", "데이터베이스의 물리적 저장 구조 설계"],
    ["논리적 설계", "데이터베이스의 논리적 구조 설계"],
    ["개념적 설계", "데이터베이스의 개념적 구조 설계"],
    ["데이터 사전(Data Dictionary)", "데이터베이스 메타데이터 저장소"],
    ["시스템 카탈로그(System Catalog)", "데이터베이스 시스템 정보 저장소"],
  ],
  6: [ // 자료구조 - extra
    ["연결 리스트(Linked List)", "노드가 포인터로 연결된 선형 자료구조"],
    ["단일 연결 리스트(Singly Linked List)", "한 방향으로만 연결된 리스트"],
    ["이중 연결 리스트(Doubly Linked List)", "양방향으로 연결된 리스트"],
    ["원형 연결 리스트(Circular Linked List)", "처음과 끝이 연결된 리스트"],
    ["스택(Stack)", "LIFO(후입선출) 방식의 선형 자료구조"],
    ["큐(Queue)", "FIFO(선입선출) 방식의 선형 자료구조"],
    ["덱(Deque)", "양쪽에서 삽입과 삭제가 가능한 큐"],
    ["우선순위 큐(Priority Queue)", "우선순위에 따라 데이터를 처리하는 큐"],
    ["해시 테이블(Hash Table)", "키-값 쌍을 저장하는 효율적인 자료구조"],
    ["해시 함수(Hash Function)", "키를 해시 값으로 변환하는 함수"],
    ["충돌 해결(Collision Resolution)", "해시 충돌을 처리하는 방법"],
    ["개방 주소법(Open Addressing)", "충돌 시 빈 버킷을 찾는 방법"],
    ["선형 탐색(Linear Probing)", "순차적으로 빈 버킷을 찾는 개방 주소법"],
    ["이차 탐색(Quadratic Probing)", "제곱수로 이동하며 빈 버킷을 찾는 방법"],
    ["이중 해싱(Double Hashing)", "두 번째 해시 함수로 충돌을 해결하는 방법"],
    ["재해싱(Rehashing)", "테이블 크기를 늘리고 다시 해싱하는 과정"],
    ["동적 배열(Dynamic Array)", "크기가 자동으로 조절되는 배열"],
    ["ArrayList(Java)", "자바의 동적 배열 구현"],
    ["벡터(Vector)", "동기화된 동적 배열"],
    ["연결 리스트 vs 배열", "메모리 할당과 접근 속도의 차이"],
    ["트리 순회(Tree Traversal)", "트리의 모든 노드를 방문하는 방법"],
    ["전위 순회(Pre-order Traversal)", "루트를 먼저 방문하는 트리 순회"],
    ["중위 순회(In-order Traversal)", "왼쪽-루트-오른쪽 순서의 트리 순회"],
    ["후위 순회(Post-order Traversal)", "왼쪽-오른쪽-루트 순서의 트리 순회"],
    ["레벨 순회(Level-order Traversal)", "레벨별로 방문하는 트리 순회"],
    ["모스 알고리즘(Morris Traversal)", "스택 없이 트리를 순회하는 알고리즘"],
    ["세그먼트 트리(Segment Tree)", "구간 질의를 빠르게 처리하는 트리"],
    ["펜윅 트리(Fenwick Tree)", "구간 합을 빠르게 계산하는 트리"],
    ["인덱스 트리(Indexed Tree)", "세그먼트 트리의 변형"],
    ["트라이(Trie)", "문자열 검색에 특화된 트리"],
    ["접미사 트리(Suffix Tree)", "문자열의 모든 접미사를 저장하는 트리"],
    ["접미사 배열(Suffix Array)", "문자열의 접미사를 정렬한 배열"],
    ["LCP 배열(Longest Common Prefix)", "접미사 배열의 LCP를 저장한 배열"],
    ["힙(Heap)", "완전 이진 트리 기반의 자료구조"],
    ["이진 힙(Binary Heap)", "가장 기본적인 힙 자료구조"],
    ["피보나치 힙(Fibonacci Heap)", "상각 시간이 우수한 힙"],
    ["이항 힙(Binomial Heap)", "이항 트리로 구성된 힙"],
    ["페어링 힙(Pairing Heap)", "구현이 간단한 힙"],
    ["좌향 트리(Leftist Tree)", "병합에 최적화된 힙"],
    ["스큐 힙(Skew Heap)", "자가 조정 힙"],
    ["그래프 표현 방법", "인접 행렬과 인접 리스트"],
    ["인접 행렬(Adjacency Matrix)", "2차원 배열로 그래프를 표현하는 방법"],
    ["인접 리스트(Adjacency List)", "연결 리스트로 그래프를 표현하는 방법"],
    ["간선 리스트(Edge List)", "간선의 리스트로 그래프를 표현하는 방법"],
    ["오일러 서킷(Eulerian Circuit)", "모든 간선을 한 번씩만 지나 시작점으로 돌아오는 경로"],
    ["해밀턴 서킷(Hamiltonian Circuit)", "모든 정점을 한 번씩만 지나는 사이클"],
    ["그래프 색칠(Graph Coloring)", "그래프의 정점에 색을 칠하는 문제"],
    ["최대 클릭(Maximum Clique)", "그래프에서 가장 큰 완전 부분 그래프"],
    ["독립 집합(Independent Set)", "서로 인접하지 않은 정점의 집합"],
    ["정점 커버(Vertex Cover)", "모든 간선이 연결된 정점을 포함하는 집합"],
    ["매칭(Matching)", "간선이 서로 겹치지 않도록 선택하는 문제"],
    ["이분 매칭(Bipartite Matching)", "이분 그래프에서의 매칭"],
    ["안정 결혼 문제(Stable Marriage)", "안정적인 짝짓기를 찾는 문제"],
    ["흐름 네트워크(Flow Network)", "용량이 있는 그래프에서의 흐름"],
    ["소스(Source)와 싱크(Sink)", "흐름 네트워크의 시작과 끝"],
    ["잔여 용량(Residual Capacity)", "남은 용량"],
    ["증가 경로(Augmenting Path)", "추가 유량을 보낼 수 있는 경로"],
    ["최소 컷(Minimum Cut)", "네트워크를 분할하는 최소 용량의 절단"],
    ["최대 유량 최소 컷 정리", "최대 유량은 최소 컷의 용량과 같다는 정리"],
    ["디닉 알고리즘(Dinic's Algorithm)", "효율적인 최대 유량 알고리즘"],
    ["이분 그래프(Bipartite Graph)", "정점을 두 그룹으로 나눌 수 있는 그래프"],
    ["완전 이분 그래프(Complete Bipartite Graph)", "모든 정점이 연결된 이분 그래프"],
    ["평면 그래프(Planar Graph)", "간선이 교차하지 않게 그릴 수 있는 그래프"],
    ["오일러 공식(Euler's Formula)", "평면 그래프에서 v-e+f=2"],
    ["쿼드 트리(Quad Tree)", "2차원 공간을 분할하는 트리"],
    ["옥트리(Octree)", "3차원 공간을 분할하는 트리"],
    ["R-트리(R-Tree)", "공간 데이터 인덱싱을 위한 트리"],
    ["B-트리(B-Tree)", "데이터베이스 인덱스에 사용되는 균형 트리"],
    ["B+ 트리(B+ Tree)", "B-트리를 확장한 인덱스 구조"],
    ["B* 트리(B* Tree)", "B+ 트리의 변형"],
    ["래드슨 트리(Radix Tree)", "비트 단위로 키를 비교하는 트리"],
    ["해시 트리(Hash Tree)", "해시 값을 사용하는 머클 트리"],
    ["머클 트리(Merkle Tree)", "블록체인에서 사용되는 해시 트리"],
    ["스킵 리스트(Skip List)", "확률적 균형 자료구조"],
    ["블룸 필터(Bloom Filter)", "집합 포함 여부를 확률적으로 확인하는 자료구조"],
    ["카운팅 블룸 필터(Counting Bloom Filter)", "삭제가 가능한 블룸 필터"],
    ["쿠쿠 필터(Cuckoo Filter)", "블룸 필터의 대안"],
    ["하이퍼로그로그(HyperLogLog)", "중복을 허용하는 집합의 크기를 추정하는 알고리즘"],
    ["Count-Min Sketch", "빈도 추정을 위한 확률적 자료구조"],
    ["최소 해시(MinHash)", "Jaccard 유사도를 추정하는 기법"],
    ["Locality-Sensitive Hashing(LSH)", "유사도 기반 해싱 기법"],
    ["비트맵(Bitmap)", "비트 배열로 데이터를 표현하는 자료구조"],
    ["비트셋(Bitset)", "비트 연산을 지원하는 집합"],
    ["희소 배열(Sparse Array)", "대부분의 값이 0인 배열을 효율적으로 저장하는 방법"],
    ["희소 행렬(Sparse Matrix)", "0이 많은 행렬을 효율적으로 저장하는 방법"],
  ],
};

async function main() {
  const existing = await new Promise(resolve => {
    http.get('http://192.168.0.3:8080/problem', res => {
      let b = '';
      res.on('data', d => b += d);
      res.on('end', () => { try { resolve(JSON.parse(b).array.length); } catch(e) { resolve(0); } });
    });
  });
  console.log(`현재 문제: ${existing}개 (목표: 10000개, 부족: ${10000 - existing}개)`);

  let totalCreated = 0;
  for (const [catSN, terms] of Object.entries(extraTerms)) {
    let created = 0;
    for (let i = 0; i < terms.length; i++) {
      const [name, def] = terms[i];
      // Variation 1: term name as question
      await createProblem(name, def, catSN); created++; totalCreated++;
      // Variation 2: "Explain..."
      await createProblem(`${name} 설명`, def, catSN); created++; totalCreated++;
      // Variation 3: What is?
      await createProblem(`${name}이란?`, `${name} 은/는 ${def}`, catSN); created++; totalCreated++;
      // Variation 4: "Describe..."
      await createProblem(`${name}을(를) 설명하시오`, def, catSN); created++; totalCreated++;
      // Variation 5: "What does...mean?"
      await createProblem(`${name}의 의미는?`, def, catSN); created++; totalCreated++;
      // Variation 6: True/False statement
      await createProblem(`${name}에 대한 설명: ${def}`, "True", catSN); created++; totalCreated++;
    }
    console.log(`  카테고리 ${catSN}: ${terms.length}개 용어 × 6 = ${created}개 문제`);
  }

  const final = await new Promise(resolve => {
    http.get('http://192.168.0.3:8080/problem', res => {
      let b = '';
      res.on('data', d => b += d);
      res.on('end', () => { try { resolve(JSON.parse(b).array.length); } catch(e) { resolve(0); } });
    });
  });
  console.log(`\n완료: 기존 ${existing}개 + 신규 ${totalCreated}개 = 총 ${final}개`);
}

main().catch(console.error);
