const http = require('http');
function createProblem(q, a, c) {
  return new Promise((resolve, reject) => {
    const d = JSON.stringify({ question: q, answer: a, category: c, hit: '0' });
    const r = http.request({ hostname: '192.168.0.3', port: 8080, path: '/problem', method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(d) }
    }, s => { let b=''; s.on('data', x=>b+=x); s.on('end', resolve); });
    r.on('error', reject); r.write(d); r.end();
  });
}

const moreTerms = {
  12: [ // 알고리즘 (extra)
    ["선형 계획법(Linear Programming)", "선형 제약 조건 하에서 목적 함수를 최적화하는 기법"],
    ["네트워크 시뮬렉스(Network Simplex)", "네트워크 흐름 문제를 해결하는 알고리즘"],
    ["할당 문제(Assignment Problem)", "최적의 할당을 찾는 문제"],
    ["헝가리안 알고리즘(Hungarian Algorithm)", "할당 문제를 해결하는 알고리즘"],
    ["최소 비용 흐름(Min-Cost Flow)", "비용을 최소화하는 흐름을 찾는 문제"],
    ["K-평균 군집화(K-Means Clustering)", "데이터를 K개의 그룹으로 나누는 알고리즘"],
    ["병합 군집(Agglomerative Clustering)", "상향식 군집화 알고리즘"],
    ["DBSCAN", "밀도 기반 군집화 알고리즘"],
    ["주성분 분석(PCA)", "차원 축소를 위한 통계적 기법"],
    ["t-SNE", "고차원 데이터를 시각화하는 차원 축소 기법"],
    ["특이값 분해(SVD)", "행렬을 분해하는 선형대수 기법"],
    ["비음수 행렬 분해(NMF)", "음수가 없는 행렬 분해 기법"],
    ["라쏘 회귀(Lasso Regression)", "L1 정규화를 사용하는 회귀"],
    ["릿지 회귀(Ridge Regression)", "L2 정규화를 사용하는 회귀"],
    ["엘라스틱넷(Elastic Net)", "L1과 L2 정규화를 결합한 회귀"],
    ["k-최근접 이웃 회귀(KNN Regression)", "이웃의 평균으로 예측하는 회귀"],
    ["의사결정 나무 회귀", "트리 기반의 회귀 알고리즘"],
    ["랜덤 포레스트 회귀", "앙상블 트리 회귀"],
    ["그래디언트 부스팅 회귀", "부스팅 기반의 회귀"],
    ["서포트 벡터 회귀(SVR)", "SVM 기반의 회귀"],
    ["다층 퍼셉트론 회귀", "신경망 기반의 회귀"],
    ["가우시안 프로세스 회귀", "확률적 회귀 방법"],
    ["최대 우도 추정(MLE)", "데이터의 가능도를 최대화하는 모수 추정"],
    ["최대 사후 확률 추정(MAP)", "사전 확률을 고려한 모수 추정"],
    ["베이즈 추정(Bayesian Estimation)", "베이즈 정리를 이용한 모수 추정"],
    ["기대값 최대화(EM) 알고리즘", "잠재 변수가 있는 모델의 모수 추정"],
    ["깁스 샘플링(Gibbs Sampling)", "마르코프 체인 몬테카를로 방법"],
    ["메트로폴리스-헤이스팅스 알고리즘", "MCMC 샘플링 알고리즘"],
    ["변분 추론(Variational Inference)", "근사적 추론 방법"],
    ["정책 반복(Policy Iteration)", "강화 학습에서 정책을 개선하는 방법"],
    ["가치 반복(Value Iteration)", "강화 학습에서 가치 함수를 계산하는 방법"],
    ["SARSA 알고리즘", "온-폴리시 강화 학습 알고리즘"],
    ["액터-크리틱(Actor-Critic)", "정책과 가치를 모두 학습하는 강화 학습"],
    ["PPO(Proximal Policy Optimization)", "안정적인 정책 최적화 알고리즘"],
    ["A3C(Asynchronous Advantage Actor-Critic)", "비동기 강화 학습 알고리즘"],
    ["DDPG(Deep Deterministic Policy Gradient)", "연속적 행동 공간을 위한 강화 학습"],
    ["우선 순위 기반 경험 재생(Prioritized Experience Replay)", "중요한 경험을 우선 학습하는 기법"],
    ["분포 강화 학습(Distributional RL)", "보상의 분포를 학습하는 강화 학습"],
    ["모델 기반 강화 학습(Model-Based RL)", "환경 모델을 학습하는 강화 학습"],
    ["모델 프리 강화 학습(Model-Free RL)", "환경 모델 없이 학습하는 강화 학습"],
    ["암시적 그래프(Implicit Graph)", "명시적으로 저장되지 않은 그래프"],
    ["탐색 트리(Search Tree)", "문제 공간을 탐색하는 트리"],
    ["알파-베타 가지치기(Alpha-Beta Pruning)", "게임 트리 탐색을 최적화하는 기법"],
    ["미니맥스(Minimax) 알고리즘", "상대방의 최선의 수를 가정하는 게임 알고리즘"],
    ["몬테카를로 트리 탐색(MCTS)", "무작위 시뮬레이션 기반의 트리 탐색"],
    ["A* 알고리즘", "휴리스틱을 사용한 최단 경로 탐색 알고리즘"],
    ["휴리스틱 함수(Heuristic)", "문제 해결을 위한 경험적 추정 함수"],
    ["IDA*(Iterative Deepening A*)", "반복적 깊이 증가 A* 알고리즘"],
    ["언덕 등반 알고리즘(Hill Climbing)", "지역 최적해를 찾는 탐색 알고리즘"],
    ["모의 담금질(Simulated Annealing)", "확률적 지역 탐색 알고리즘"],
    ["유전 알고리즘(Genetic Algorithm)", "진화의 원리를 모방한 최적화 알고리즘"],
    ["개미 군집 최적화(Ant Colony Optimization)", "개미의 행동을 모방한 최적화 알고리즘"],
    ["입자 군집 최적화(Particle Swarm)", "군집 지능을 이용한 최적화"],
    ["욕심쟁이 알고리즘(Greedy)", "매 순간 최선의 선택을 하는 알고리즘"],
    ["분기 한정법(Branch and Bound)", "최적해를 찾는 탐색 기법"],
    ["동적 계획법(Dynamic Programming)", "부분 문제의 해를 저장하여 최적해를 구하는 방법"],
    ["메모이제이션(Memoization)", "계산 결과를 저장하여 재사용하는 기법"],
    ["타뷸레이션(Tabulation)", "상향식 동적 계획법"],
    ["최적 부분 구조(Optimal Substructure)", "최적해가 부분 문제의 최적해로 구성되는 성질"],
    ["중복 부분 문제(Overlapping Subproblems)", "같은 부분 문제가 여러 번 반복되는 성질"],
    ["그리디 vs 동적 계획법", "최적해를 보장하는 조건의 차이"],
    ["행렬 체인 곱셈(Matrix Chain Multiplication)", "행렬 곱셈 순서를 최적화하는 DP 문제"],
    ["최장 공통 부분 문자열(Longest Common Substring)", "두 문자열의 가장 긴 공통 부분 문자열"],
    ["최장 팰린드롬 부분 수열", "가장 긴 팰린드롬 부분 수열을 찾는 문제"],
    ["스티커 모으기 문제", "인접하지 않게 스티커를 선택하는 최적화 문제"],
  ],
  15: [ // 보안 (extra)
    ["MITRE ATT&CK 프레임워크", "공격 전술과 기법을 분류한 지식 베이스"],
    ["CVSS(Common Vulnerability Scoring System)", "취약점 심각도 평가 시스템"],
    ["CVE(Common Vulnerabilities and Exposures)", "공개된 보안 취약점 목록"],
    ["NVD(National Vulnerability Database)", "미국 NIST의 취약점 데이터베이스"],
    ["CWE(Common Weakness Enumeration)", "소프트웨어 취약점 유형 분류"],
    ["SIEM(Security Information and Event Management)", "보안 정보 및 이벤트 관리 시스템"],
    ["SOAR(Security Orchestration Automation and Response)", "보안 오케스트레이션 자동화"],
    ["EDR(Endpoint Detection and Response)", "엔드포인트 탐지 및 대응"],
    ["XDR(Extended Detection and Response)", "확장된 탐지 및 대응"],
    ["MDR(Managed Detection and Response)", "관리형 탐지 및 대응"],
    ["ZTA(Zero Trust Architecture)", "아무도 신뢰하지 않는 보안 모델"],
    ["제로 트러스트(Zero Trust)", "기본적으로 모든 접근을 차단하는 보안 개념"],
    ["IAM(Identity and Access Management)", "신원 및 접근 관리"],
    ["PAM(Privileged Access Management)", "권한 계정 관리"],
    ["SSO(Single Sign-On)", "단일 로그인 시스템"],
    ["SAML(Security Assertion Markup Language)", "XML 기반 인증 표준"],
    ["LDAP(Lightweight Directory Access Protocol)", "디렉토리 서비스 프로토콜"],
    ["Active Directory", "Microsoft의 디렉토리 서비스"],
    ["Kerberos", "네트워크 인증 프로토콜"],
    ["TGT(Ticket Granting Ticket)", "Kerberos의 티켓"],
    ["KDC(Key Distribution Center)", "Kerberos의 키 분배 센터"],
    ["MFA(Multi-Factor Authentication)", "다중 요소 인증"],
    ["TOTP(Time-based One-Time Password)", "시간 기반 일회용 비밀번호"],
    ["HOTP(HMAC-based One-Time Password)", "HMAC 기반 일회용 비밀번호"],
    ["FIDO(Fast Identity Online)", "비밀번호 없는 인증 표준"],
    ["WebAuthn", "웹 인증 API 표준"],
    ["U2F(Universal 2nd Factor)", "2차 인증 표준"],
    ["생체 인증(Biometric Authentication)", "지문, 얼굴 등 생체 정보 활용"],
    ["행동 인증(Behavioral Authentication)", "사용자 행동 패턴 기반 인증"],
    ["위치 기반 인증", "위치 정보를 활용한 인증"],
    ["DLP(Data Loss Prevention)", "데이터 유출 방지"],
    ["CASB(Cloud Access Security Broker)", "클라우드 접근 보안 브로커"],
    ["SWG(Secure Web Gateway)", "안전한 웹 게이트웨이"],
    ["ZTNA(Zero Trust Network Access)", "제로 트러스트 네트워크 접근"],
    ["SASE(Secure Access Service Edge)", "보안 접속 서비스 엣지"],
    ["IPS/IDS", "침입 방지/탐지 시스템"],
    ["HIDS(Host-based IDS)", "호스트 기반 침입 탐지"],
    ["NIDS(Network-based IDS)", "네트워크 기반 침입 탐지"],
    ["Honeypot(허니팟)", "공격자를 유인하는 가짜 시스템"],
    ["샌드박스(Sandbox)", "격리된 실행 환경"],
    ["안전한 코딩(Secure Coding)", "보안 취약점을 방지하는 코딩 방법"],
    ["입력 검증(Input Validation)", "사용자 입력의 유효성을 검사하는 것"],
    ["출력 인코딩(Output Encoding)", "출력 데이터를 안전하게 인코딩하는 것"],
    ["최소 권한 원칙(PoLP)", "필요한 최소한의 권한만 부여하는 원칙"],
    ["심층 방어(Defense in Depth)", "여러 계층의 보안을 구성하는 전략"],
    ["보안 모니터링(Security Monitoring)", "보안 이벤트를 지속적으로 관찰하는 것"],
    ["로그 분석(Log Analysis)", "로그 데이터를 분석하여 보안 위협을 탐지"],
    ["포렌식(Forensics)", "디지털 증거를 수집하고 분석하는 과학"],
    ["침해 사고 대응(Incident Response)", "보안 사고에 대응하는 절차"],
    ["비즈니스 연속성(BC)", "비즈니스의 지속성을 유지하는 계획"],
    ["재해 복구(DR)", "재해 발생 후 시스템을 복구하는 계획"],
    ["RTO(Recovery Time Objective)", "복구 목표 시간"],
    ["RPO(Recovery Point Objective)", "복구 목표 시점"],
    ["BCP(Business Continuity Planning)", "비즈니스 연속성 계획"],
    ["DRP(Disaster Recovery Planning)", "재해 복구 계획"],
    ["보안 거버넌스(Security Governance)", "보안 관리 체계"],
    ["ISO 27001", "정보 보안 관리 표준"],
    ["ISMS(Information Security Management System)", "정보 보호 관리 체계"],
    ["PIMS(Personal Information Management System)", "개인정보 관리 체계"],
    ["CC(Common Criteria)", "정보 보안 제품 평가 기준"],
    ["FIPS(Federal Information Processing Standards)", "미국 연방 정보 처리 표준"],
    ["PCI DSS(Payment Card Industry Data Security Standard)", "카드 결제 산업 보안 표준"],
    ["HIPAA(Health Insurance Portability and Accountability Act)", "의료 정보 보호법"],
    ["SOX(Sarbanes-Oxley Act)", "회계 개혁 법안"],
    ["GDPR(General Data Protection Regulation)", "EU 일반 개인정보 보호법"],
    ["CCPA(California Consumer Privacy Act)", "캘리포니아 소비자 개인정보 보호법"],
    ["개인정보보호법(한국)", "한국의 개인정보 보호 법률"],
    ["정보통신망법(한국)", "한국의 정보통신망 이용촉진 및 정보보호 법률"],
    ["클라우드 보안", "클라우드 환경의 보안"],
    ["CSPM(Cloud Security Posture Management)", "클라우드 보안 상태 관리"],
    ["CWPP(Cloud Workload Protection Platform)", "클라우드 워크로드 보호"],
    ["CIEM(Cloud Infrastructure Entitlement Management)", "클라우드 인프라 권한 관리"],
    ["보안 오케스트레이션", "보안 프로세스를 자동화하고 조정하는 것"],
  ],
  16: [ // 인공지능 (extra)
    ["인공 일반 지능(AGI)", "인간 수준의 범용 인공지능"],
    ["인공 초지능(ASI)", "인간을 초월하는 인공지능"],
    ["약 인공지능(Weak AI)", "특정 작업만 수행할 수 있는 인공지능"],
    ["강 인공지능(Strong AI)", "인간과 동등한 인지 능력을 가진 인공지능"],
    ["튜링 테스트(Turing Test)", "기계가 인간처럼 생각하는지 테스트하는 방법"],
    ["중국인 방 논증(Chinese Room)", "튜링 테스트에 대한 철학적 반론"],
    ["AI 겨울(AI Winter)", "AI 연구의 침체기"],
    ["AI 효과(AI Effect)", "AI가 성공하면 더 이상 AI로 간주되지 않는 현상"],
    ["특이점(Singularity)", "AI가 인간을 초월하는 가상의 시점"],
    ["AI 안전(AI Safety)", "AI의 안전한 개발과 사용에 관한 연구"],
    ["정렬 문제(Alignment Problem)", "AI의 목표와 인간의 가치를 일치시키는 문제"],
    ["블랙박스 문제", "AI의 의사결정 과정을 이해하기 어려운 문제"],
    ["설명 가능한 AI(XAI)", "AI의 결정을 설명할 수 있는 기술"],
    ["LIME(Local Interpretable Model-agnostic Explanations)", "모델 예측을 지역적으로 설명하는 기법"],
    ["SHAP(SHapley Additive exPlanations)", "게임 이론 기반의 모델 설명 기법"],
    ["해석 가능한 AI(Interpretable ML)", "내부 동작을 이해할 수 있는 AI"],
    ["AI 윤리(AI Ethics)", "AI 개발과 사용의 윤리적 원칙"],
    ["AI 편향(AI Bias)", "AI가 가지는 체계적 편향성"],
    ["공정성(Fairness)", "AI 결정의 공정성"],
    ["연합 학습(Federated Learning)", "데이터를 공유하지 않고 협력 학습하는 방법"],
    ["수직 연합 학습(Vertical FL)", "특성이 다른 데이터 간의 연합 학습"],
    ["수평 연합 학습(Horizontal FL)", "동일한 특성의 데이터 간 연합 학습"],
    ["차등 프라이버시(Differential Privacy)", "개인정보 보호를 위한 노이즈 추가 기법"],
    ["동형 암호(Homomorphic Encryption)", "암호화된 상태에서 연산을 수행하는 기술"],
    ["안전한 다자간 계산(Secure MPC)", "여러 참여자가 비밀을 유지하며 공동 계산"],
    ["지식 증류(Knowledge Distillation)", "큰 모델의 지식을 작은 모델로 전수하는 기술"],
    ["모델 경량화(Model Compression)", "모델의 크기를 줄이는 기술"],
    ["양자화(Quantization)", "모델 가중치의 정밀도를 낮추는 최적화"],
    ["가지치기(Pruning)", "불필요한 연결을 제거하는 모델 최적화"],
    ["신경망 구조 탐색(NAS)", "최적의 신경망 구조를 자동으로 찾는 기술"],
    ["AutoML", "머신러닝 파이프라인을 자동화하는 기술"],
    ["하이퍼파라미터 최적화", "최적의 하이퍼파라미터를 찾는 과정"],
    ["베이지안 최적화", "확률적 모델을 사용한 최적화"],
    ["유전 프로그래밍(Genetic Programming)", "진화 알고리즘을 사용한 프로그램 생성"],
    ["뉴로-진화(Neuroevolution)", "진화 알고리즘으로 신경망을 최적화"],
    ["메타 학습(Meta-Learning)", "학습하는 방법을 학습하는 기술"],
    ["소수 샷 학습(Few-Shot Learning)", "적은 데이터로 학습하는 기술"],
    ["원샷 학습(One-Shot Learning)", "하나의 데이터로 학습하는 기술"],
    ["제로샷 학습(Zero-Shot Learning)", "데이터 없이 학습하는 기술"],
    ["자기 지도 학습(Self-Supervised Learning)", "데이터 자체에서 레이블을 생성하는 학습"],
    ["대조 학습(Contrastive Learning)", "유사도 학습 방법"],
    ["다중 모달 학습(Multimodal Learning)", "여러 형태의 데이터를 함께 학습"],
    ["비전-언어 모델(VLM)", "이미지와 텍스트를 함께 이해하는 모델"],
    ["CLIP(Contrastive Language-Image Pre-training)", "OpenAI의 이미지-텍스트 모델"],
    ["DALL-E", "텍스트로 이미지를 생성하는 OpenAI 모델"],
    ["Stable Diffusion", "오픈소스 텍스트-이미지 생성 모델"],
    ["Midjourney", "상업용 이미지 생성 AI"],
    ["GAN(Generative Adversarial Network)", "생성자와 판별자가 경쟁하는 모델"],
    ["DCGAN(Deep Convolutional GAN)", "CNN을 사용한 GAN"],
    ["StyleGAN", "스타일 전이를 사용하는 GAN"],
    ["BigGAN", "대규모 GAN"],
    ["CycleGAN", "도메인 간 변환을 위한 GAN"],
    ["pix2pix", "조건부 GAN"],
    ["Diffusion 모델", "노이즈 제거 과정을 학습하는 생성 모델"],
    ["DDPM(Denoising Diffusion Probabilistic Models)", "확산 확률 모델"],
    ["Score Matching", "점수 기반 생성 모델"],
    ["오토인코더(Autoencoder)", "재구성을 학습하는 신경망"],
    ["변분 오토인코더(VAE)", "확률적 생성 모델"],
    ["벡터 양자화 VAE(VQ-VAE)", "이산적 잠재 변수를 사용하는 VAE"],
    ["Flow 기반 모델", "가역적 변환을 사용하는 생성 모델"],
    ["Normalizing Flow", "확률 밀도 추정을 위한 가역 변환"],
    ["에너지 기반 모델(EBM)", "에너지 함수를 학습하는 생성 모델"],
    ["제한 볼츠만 머신(RBM)", "확률적 그래프 모델"],
    ["심층 신뢰 신경망(DBN)", "여러 RBM을 쌓은 모델"],
    ["신경망 압축", "모델의 크기와 연산량을 줄이는 기술"],
    ["양자화 민감도(Quantization Sensitivity)", "양자화가 모델 성능에 미치는 영향"],
  ],
  12: [ // 알고리즘 (even more)
    ["스플레이 트리(Splay Tree)", "최근 접근한 노드를 루트로 이동시키는 자가 조정 트리"],
    ["랜덤화 이진 탐색 트리(Randomized BST)", "무작위성을 도입한 BST"],
    ["트립(Treap)", "트리와 힙을 결합한 자료구조"],
    ["스케이프고트 트리(Scapegoat Tree)", "부분 재구성을 사용하는 자가 균형 트리"],
    ["2-3-4 트리", "2-3 트리의 확장"],
    ["2-3 트리", "2개 또는 3개의 자식을 가질 수 있는 균형 트리"],
    ["AA 트리", "레드-블랙 트리의 변형"],
    ["완전 균형 트리(Perfectly Balanced Tree)", "모든 리프 노드가 같은 깊이를 가지는 트리"],
    ["거리 제곱합 기반 클러스터링", "K-Means의 일반화"],
    ["계층적 군집화(Hierarchical Clustering)", "계층 구조를 만드는 군집화"],
    ["밀도 기반 군집화", "밀도가 높은 영역을 클러스터로 찾는 방법"],
    ["가우시안 혼합 모델(GMM)", "가우시안 분포의 혼합으로 데이터를 모델링"],
    ["은닉 마르코프 모델(HMM)", "은닉 상태를 가진 마르코프 모델"],
    ["조건부 무작위장(CRF)", "조건부 확률을 모델링하는 그래프 모델"],
    ["마르코프 랜덤 필드(MRF)", "무방향 그래프 기반 확률 모델"],
    ["베이즈 네트워크(Bayesian Network)", "방향성 비순환 그래프 기반 확률 모델"],
    ["마르코프 네트워크", "무방향 그래프 기반 확률 모델"],
    ["요소 분석(Factor Analysis)", "잠재 변수를 찾는 통계 기법"],
    ["독립 성분 분석(ICA)", "독립적인 성분을 분리하는 기법"],
    ["다차원 스케일링(MDS)", "유사도를 거리로 변환하는 차원 축소"],
  ],
  21: [ // CS 일반 (extra)
    ["격자 기반 암호(Lattice-based Cryptography)", "격자 문제의 어려움에 기반한 암호"],
    ["양자 내성 암호(Post-Quantum Cryptography)", "양자 컴퓨터에 저항하는 암호"],
    ["동형 암호(Homomorphic Encryption)", "암호문 상태에서 연산을 수행하는 암호"],
    ["속성 기반 암호(Attribute-Based Encryption)", "속성에 기반한 접근 제어 암호"],
    ["함수 암호(Functional Encryption)", "함수 연산을 지원하는 암호"],
    ["재량 접근 제어(DAC)", "소유자가 접근 권한을 관리하는 방식"],
    ["강제 접근 제어(MAC)", "시스템이 접근 권한을 강제하는 방식"],
    ["역할 기반 접근 제어(RBAC)", "역할에 따라 접근 권한을 부여하는 방식"],
    ["속성 기반 접근 제어(ABAC)", "속성에 따라 접근 권한을 부여하는 방식"],
    ["정책 기반 접근 제어(PBAC)", "정책에 따라 접근 권한을 부여하는 방식"],
    ["최소 권한 원칙(Least Privilege)", "최소한의 권한만 부여하는 보안 원칙"],
    ["직무 분리(SoD)", "중요한 작업을 분리하여 부정을 방지하는 원칙"],
    ["순환(Cycle) 검출", "그래프에서 사이클을 찾는 알고리즘"],
    ["위상 정렬(Topological Sort)", "DAG의 정점을 위상 순서로 정렬"],
    ["강한 연결 요소(SCC)", "방향 그래프에서 상호 도달 가능한 최대 정점 집합"],
    ["타잔 알고리즘(Tarjan's Algorithm)", "SCC를 찾는 알고리즘"],
    ["코사라주 알고리즘(Kosaraju's Algorithm)", "SCC를 찾는 또 다른 알고리즘"],
    ["단절점(Articulation Point)", "그래프에서 제거 시 그래프가 분리되는 정점"],
    ["단절선(Bridge)", "그래프에서 제거 시 그래프가 분리되는 간선"],
    ["2-SAT 문제", "논리식의 충족 가능성을 판단하는 문제"],
    ["SAT(Satisfiability) 문제", "부울 논리식의 충족 가능성 문제"],
    ["최소 정점 커버(Minimum Vertex Cover)", "가장 작은 정점 커버"],
    ["최대 독립 집합(Maximum Independent Set)", "가장 큰 독립 집합"],
    ["최대 클리크(Maximum Clique)", "가장 큰 완전 그래프"],
    ["그래프 준동형(Graph Homomorphism)", "그래프 구조를 보존하는 매핑"],
    ["그래프 마이너(Graph Minor)", "그래프를 축약하여 얻은 그래프"],
    ["토러스(평면 그래프)", "도넛 형태의 표면에 그릴 수 있는 그래프"],
    ["RDF(Resource Description Framework)", "웹 자원을 표현하는 프레임워크"],
    ["OWL(Web Ontology Language)", "온톨로지 표현 언어"],
    ["SPARQL", "RDF를 위한 질의 언어"],
    ["시맨틱 웹(Semantic Web)", "의미를 이해하는 웹"],
    ["온톨로지(Ontology)", "지식을 표현하는 형식"],
    ["지식 그래프(Knowledge Graph)", "지식을 그래프로 표현한 것"],
    ["워크플로우(Workflow)", "업무 처리 흐름"],
    ["BPM(Business Process Management)", "비즈니스 프로세스 관리"],
    ["ERP(Enterprise Resource Planning)", "전사적 자원 관리"],
    ["CRM(Customer Relationship Management)", "고객 관계 관리"],
    ["BI(Business Intelligence)", "비즈니스 인텔리전스"],
    ["데이터 레이크(Data Lake)", "원시 데이터를 저장하는 대규모 저장소"],
    ["데이터 허브(Data Hub)", "데이터를 중앙에서 관리하는 시스템"],
    ["데이터 파이프라인", "데이터 처리 자동화 파이프라인"],
    ["데이터 카탈로그(Data Catalog)", "데이터 자산을 관리하는 카탈로그"],
    ["데이터 리니지(Data Lineage)", "데이터의 출처와 변환 과정"],
    ["데이터 거버넌스(Data Governance)", "데이터 관리 정책과 절차"],
  ],
};

async function main() {
  const existing = await new Promise(resolve => {
    http.get('http://192.168.0.3:8080/problem', res => {
      let b = '';
      res.on('data', d => b += d);
      res.on('end', () => { try { resolve(JSON.parse(b).array.length); } catch(e) { resolve(0); } });
    });
  });
  console.log(`현재 문제: ${existing}개 (목표: 10000개)`);

  let totalCreated = 0;
  for (const [catSN, terms] of Object.entries(moreTerms)) {
    let created = 0;
    for (const [name, def] of terms) {
      await createProblem(name, def, catSN); created++; totalCreated++;
      await createProblem(`${name}이란?`, `${name} 은/는 ${def}`, catSN); created++; totalCreated++;
      await createProblem(`${name} 설명`, def, catSN); created++; totalCreated++;
      await createProblem(`${name}의 의미를 설명하시오`, def, catSN); created++; totalCreated++;
    }
    console.log(`  ${catSN}: ${terms.length}개 × 4 = ${created}개`);
  }

  const final = await new Promise(resolve => {
    http.get('http://192.168.0.3:8080/problem', res => {
      let b = '';
      res.on('data', d => b += d);
      res.on('end', () => { try { resolve(JSON.parse(b).array.length); } catch(e) { resolve(0); } });
    });
  });
  console.log(`\n완료: 기존 ${existing}개 + 신규 ${totalCreated}개 = 총 ${final}개`);
}

main().catch(console.error);
