const http = require('http');
function cp(q, a, c) {
  return new Promise((resolve, reject) => {
    const d = JSON.stringify({ question: q, answer: a, category: c, hit: '0' });
    const r = http.request({ hostname: '192.168.0.3', port: 8080, path: '/problem', method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(d) }
    }, s => { let b=''; s.on('data', x=>b+=x); s.on('end', resolve); });
    r.on('error', reject); r.write(d); r.end();
  });
}
const data = {
  13: [
    ["SOLID 원칙", "객체 지향 설계의 다섯 가지 기본 원칙"],
    ["단일 책임 원칙(SRP)", "클래스는 하나의 책임만 가져야 한다는 원칙"],
    ["개방-폐쇄 원칙(OCP)", "확장에는 열려 있고 변경에는 닫혀 있어야 한다는 원칙"],
    ["리스코프 치환 원칙(LSP)", "자식 클래스는 부모 클래스를 대체할 수 있어야 한다는 원칙"],
    ["인터페이스 분리 원칙(ISP)", "클라이언트는 자신이 사용하지 않는 인터페이스에 의존하면 안 된다는 원칙"],
    ["의존관계 역전 원칙(DIP)", "추상화에 의존하고 구체화에 의존하면 안 된다는 원칙"],
    ["DRY(Don't Repeat Yourself)", "코드 중복을 피해야 한다는 원칙"],
    ["KISS(Keep It Simple, Stupid)", "단순함을 유지해야 한다는 원칙"],
    ["YAGNI(You Aren't Gonna Need It)", "필요하지 않은 기능을 미리 만들지 말라는 원칙"],
    ["관심사 분리(Separation of Concerns)", "서로 다른 관심사를 분리하는 설계 원칙"],
    ["테스트 용이성(Testability)", "소프트웨어가 테스트하기 쉬운 정도"],
    ["유지보수성(Maintainability)", "소프트웨어가 유지보수하기 쉬운 정도"],
    ["가독성(Readability)", "소스 코드가 읽기 쉬운 정도"],
    ["재사용성(Reusability)", "소프트웨어 구성 요소를 재사용할 수 있는 정도"],
    ["확장성(Extensibility)", "소프트웨어가 확장되기 쉬운 정도"],
    ["결합도(Coupling)", "모듈 간의 의존성 정도"],
    ["응집도(Cohesion)", "모듈 내 요소들의 관련성 정도"],
    ["낮은 결합도, 높은 응집도", "좋은 소프트웨어 설계의 핵심 원칙"],
    ["정적 팩토리 메서드(Static Factory Method)", "객체 생성을 정적 메서드로 대체하는 패턴"],
    ["빌더 패턴(Builder)", "복잡한 객체를 단계적으로 생성하는 패턴"],
    ["프로토타입 패턴(Prototype)", "객체를 복제하여 생성하는 패턴"],
    ["추상 팩토리 패턴(Abstract Factory)", "관련 객체군을 생성하는 인터페이스를 제공하는 패턴"],
    ["플라이웨이트 패턴(Flyweight)", "공유를 통해 많은 객체를 효율적으로 지원하는 패턴"],
    ["브리지 패턴(Bridge)", "추상과 구현을 분리하는 패턴"],
    ["컴포지트 패턴(Composite)", "부분-전체 관계를 트리로 표현하는 패턴"],
    ["퍼사드 패턴(Facade)", "복잡한 서브시스템에 간단한 인터페이스를 제공하는 패턴"],
    ["비지터 패턴(Visitor)", "객체 구조를 변경하지 않고 새로운 연산을 추가하는 패턴"],
    ["인터프리터 패턴(Interpreter)", "문법 규칙을 클래스로 표현하는 패턴"],
    ["이터레이터 패턴(Iterator)", "컬렉션을 순회하는 방법을 제공하는 패턴"],
    ["메멘토 패턴(Memento)", "객체의 상태를 저장하고 복원하는 패턴"],
    ["스테이트 패턴(State)", "상태에 따라 행동이 변하는 패턴"],
    ["템플릿 메서드 패턴(Template Method)", "알고리즘의 뼈대를 정의하는 패턴"],
    ["비즈니스 로직", "핵심 업무 규칙을 처리하는 코드"],
    ["레이어드 아키텍처(Layered Architecture)", "계층으로 구성된 아키텍처"],
    ["헥사고날 아키텍처(Hexagonal Architecture)", "포트와 어댑터로 구성된 아키텍처"],
    ["클린 아키텍처(Clean Architecture)", "의존성 규칙을 따르는 아키텍처"],
    ["이벤트 기반 아키텍처(Event-Driven)", "이벤트를 기반으로 동작하는 아키텍처"],
    ["도메인 주도 설계(DDD)", "도메인을 중심으로 설계하는 방법론"],
    ["CQRS(Command Query Responsibility Segregation)", "명령과 조회의 책임을 분리하는 패턴"],
    ["이벤트 소싱(Event Sourcing)", "상태 대신 이벤트를 저장하는 방식"],
    ["소프트웨어 트랜지스터", "소프트웨어 개발 방법론의 진화"],
    ["프로토콜 버퍼(Protocol Buffers)", "Google의 효율적인 직렬화 형식"],
    ["Apache Thrift", "Facebook의 직렬화 및 RPC 프레임워크"],
    ["gRPC", "Google의 고성능 RPC 프레임워크"],
    ["FlatBuffers", "Google의 효율적인 직렬화 라이브러리"],
    ["MessagePack", "효율적인 이진 직렬화 형식"],
    ["BSON", "MongoDB의 이진 JSON 형식"],
    ["Avro", "Hadoop의 데이터 직렬화 형식"],
    ["Parquet", "컬럼 기반 저장 형식"],
    ["ORC(Optimized Row Columnar)", "Hive의 컬럼 기반 저장 형식"],
    ["Arrow", "인-메모리 컬럼 형식"],
    ["Cap'n Proto", "고속 직렬화 형식"],
    ["CBOR(Concise Binary Object Representation)", "JSON의 이진 표현"],
    ["TOML(Tom's Obvious Minimal Language)", "설정 파일 형식"],
    ["HOCON(Human-Optimized Config Object Notation)", "설정 파일 형식"],
    ["INI 파일", "간단한 설정 파일 형식"],
    ["타입 안전성(Type Safety)", "타입 오류를 방지하는 언어의 특성"],
    ["메모리 안전성(Memory Safety)", "메모리 오류를 방지하는 언어의 특성"],
    ["널 안전성(Null Safety)", "널 참조 오류를 방지하는 언어의 특성"],
    ["소유권(Ownership)", "메모리 소유권을 관리하는 Rust의 개념"],
    ["빌림(Borrowing)", "소유권을 임대하는 Rust의 개념"],
    ["수명(Lifetime)", "참조의 유효 기간을 나타내는 Rust의 개념"],
    ["Rust의 소유권 시스템", "메모리 안전성을 보장하는 Rust의 핵심 기능"],
    ["Go 루틴(Goroutine)", "Go 언어의 경량 스레드"],
    ["채널(Channel)", "Go 언어의 동시성 통신 메커니즘"],
    ["select 문(Go)", "여러 채널을 기다리는 Go의 제어문"],
    ["defer(Go)", "함수 종료 시 실행을 보장하는 Go의 키워드"],
    ["인터페이스(Go)", "메서드 집합을 정의하는 Go의 타입"],
    ["구조체(Go)", "필드의 집합을 정의하는 Go의 타입"],
    ["메서드(Go)", "특정 타입에 연결된 함수"],
    ["패키지(Go)", "Go 코드의 모듈 단위"],
    ["모듈(Go Module)", "Go의 의존성 관리 시스템"],
    ["Go의 동시성 모델", "고루틴과 채널을 기반으로 하는 Go의 동시성"],
    ["러스트(Rust)", "메모리 안전성과 성능을 강조하는 시스템 프로그래밍 언어"],
    ["고(Go)", "Google이 개발한 간결하고 효율적인 프로그래밍 언어"],
    ["코틀린(Kotlin)", "JetBrains가 개발한 JVM 기반 현대적 언어"],
    ["스위프트(Swift)", "Apple이 개발한 현대적인 프로그래밍 언어"],
    ["타입스크립트(TypeScript)", "Microsoft가 개발한 JavaScript의 상위 집합 언어"],
    ["러스트의 열거형(Enum)", "여러 변형을 가질 수 있는 Rust의 타입"],
    ["러스트의 패턴 매칭", "값의 구조를 분해하는 Rust의 기능"],
    ["옵셔널(Optional)", "값이 없을 수 있음을 나타내는 타입"],
    ["래퍼 타입(Wrapper Type)", "기본 타입을 감싸는 타입"],
    ["뉴타입(Newtype) 패턴", "기존 타입에 새로운 이름을 부여하는 패턴"],
    ["타입 클래스(Type Class)", "Haskell의 다형성을 지원하는 개념"],
    ["모나드(Monad)", "함수형 프로그래밍의 추상적 인터페이스"],
    ["펑터(Functor)", "매핑이 가능한 컨테이너를 나타내는 타입 클래스"],
    ["애플리케이티브 펑터(Applicative)", "함수를 컨테이너에 적용할 수 있는 펑터"],
    ["모노이드(Monoid)", "결합 법칙과 항등원을 가진 대수적 구조"],
    ["세미그룹(Semigroup)", "결합 법칙을 만족하는 이항 연산을 가진 대수적 구조"],
    ["고계 함수(Higher-Order Function)", "함수를 인자나 반환값으로 다루는 함수"],
    ["부분 적용(Partial Application)", "함수의 일부 인자를 고정하는 기법"],
    ["커링(Currying)", "여러 인자를 받는 함수를 단일 인자 함수의 체인으로 변환"],
    ["지연 평가(Lazy Evaluation)", "값이 필요할 때까지 계산을 미루는 기법"],
    ["패턴 매칭(Pattern Matching)", "값의 구조를 검사하는 기능"],
    ["대수적 데이터 타입(ADT)", "여러 타입을 조합하여 새로운 타입을 정의하는 방식"],
    ["불변 자료구조(Immutable Data Structure)", "변경이 불가능한 자료구조"],
    ["영속적 자료구조(Persistent Data Structure)", "변경 시 이전 버전이 유지되는 자료구조"],
  ],
  14: [
    ["소프트웨어 아키텍처 스타일", "시스템의 구조적 패턴과 스타일"],
    ["파이프-필터 아키텍처(Pipe-Filter)", "데이터 흐름을 처리하는 아키텍처"],
    ["클라이언트-서버 아키텍처", "클라이언트와 서버로 분리된 아키텍처"],
    ["계층형 아키텍처(Layered)", "계층으로 구성된 전통적 아키텍처"],
    ["마이크로커널 아키텍처", "최소한의 커널을 가진 아키텍처"],
    ["블랙보드 아키텍처(Blackboard)", "공유 데이터 저장소를 사용하는 아키텍처"],
    ["브로커 패턴(Broker)", "분산 컴포넌트 간 통신을 중개하는 아키텍처"],
    ["MVC(Model-View-Controller)", "모델, 뷰, 컨트롤러로 구성된 아키텍처"],
    ["MVP(Model-View-Presenter)", "MVC의 변형 아키텍처"],
    ["MVVM(Model-View-ViewModel)", "데이터 바인딩을 강조하는 아키텍처"],
    ["VIPER", "iOS 앱을 위한 모듈식 아키텍처"],
    ["Clean Swift", "iOS를 위한 클린 아키텍처"],
    ["리액티브 아키텍처(Reactive)", "데이터 흐름과 변화 전파에 중점을 둔 아키텍처"],
    ["옵저버블(Observable)", "관찰 가능한 데이터 스트림"],
    ["RxJava/RxSwift/RxJS", "ReactiveX 라이브러리"],
    ["Combine", "Apple의 리액티브 프레임워크"],
    ["리액티브 스트림(Reactive Streams)", "비동기 스트림 처리를 위한 표준"],
    ["Flux", "단방향 데이터 흐름 아키텍처"],
    ["Redux", "Flux 패턴의 구현"],
    ["NgRx", "Angular의 Redux"],
    ["Vuex", "Vue.js의 상태 관리"],
    ["MobX", "반응형 상태 관리 라이브러리"],
    ["Recoil", "React의 상태 관리 라이브러리"],
    ["Zustand", "간단한 React 상태 관리"],
    ["Jotai", "원자적 React 상태 관리"],
    ["전역 상태 관리(Global State)", "전역적으로 공유되는 상태 관리"],
    ["로컬 상태(Local State)", "컴포넌트 내부에서만 사용되는 상태"],
    ["상태 끌어올리기(Lifting State Up)", "상태를 공통 부모로 이동시키는 패턴"],
    ["컨텍스트(Context)", "React의 전역 상태 전달 메커니즘"],
    ["Props 드릴링(Props Drilling)", "여러 계층으로 props를 전달하는 현상"],
    ["하이어 오더 컴포넌트(HOC)", "컴포넌트를 인자로 받아 새 컴포넌트를 반환하는 패턴"],
    ["렌더 프롭스(Render Props)", "함수 prop을 사용하는 패턴"],
    ["훅(Hooks)", "React의 함수형 컴포넌트에서 상태와 생명주기를 사용하는 기능"],
    ["커스텀 훅(Custom Hooks)", "로직을 재사용하기 위한 사용자 정의 훅"],
    ["useEffect", "React의 사이드 이펙트 처리 훅"],
    ["useMemo", "React의 메모이제이션 훅"],
    ["useCallback", "React의 콜백 메모이제이션 훅"],
    ["useRef", "React의 참조 훅"],
    ["가상 DOM(Virtual DOM)", "실제 DOM을 추상화한 가상 표현"],
    ["재조정(Reconciliation)", "React의 가상 DOM 업데이트 알고리즘"],
    ["diffing 알고리즘", "가상 DOM의 변경 사항을 비교하는 알고리즘"],
    ["키(Key) 속성", "React에서 요소를 식별하는 특수 속성"],
    ["지연 로딩(Lazy Loading)", "필요할 때까지 로딩을 지연하는 기법"],
    ["코드 스플리팅(Code Splitting)", "코드를 여러 청크로 분할하는 기법"],
    ["트리 쉐이킹(Tree Shaking)", "사용되지 않는 코드를 제거하는 최적화"],
    ["웹팩(Webpack)", "모듈 번들러"],
    ["비트(Vite)", "차세대 프론트엔드 빌드 도구"],
    ["esbuild", "고속 JavaScript 번들러"],
    ["SWC", "Rust 기반의 고속 JavaScript/TypeScript 컴파일러"],
    ["Rollup", "ES 모듈 번들러"],
    ["Parcel", "설정이 필요 없는 번들러"],
    ["Snowpack", "ESM 기반의 빌드 도구"],
    ["Turbopack", "Rust 기반의 증분 번들러"],
    ["Babel", "JavaScript 트랜스파일러"],
    ["tsc(TypeScript Compiler)", "TypeScript 컴파일러"],
    ["ESLint", "JavaScript 정적 분석 도구"],
    ["Prettier", "코드 포맷터"],
    ["Stylelint", "CSS 정적 분석 도구"],
    ["Husky", "Git 훅 관리 도구"],
    ["lint-staged", "스테이지된 파일만 린트하는 도구"],
    ["commitlint", "커밋 메시지 검사 도구"],
    ["Semantic Versioning", "의미론적 버전 관리"],
    ["Major.Minor.Patch", "주.부.수 버전 관리 체계"],
    ["유의적 버전(SemVer)", "API 호환성을 표현하는 버전 관리"],
    ["CalVer(Calendar Versioning)", "날짜 기반 버전 관리"],
    ["CHANGELOG", "변경 사항을 기록하는 문서"],
    ["릴리즈 노트(Release Notes)", "새 버전의 변경 사항을 설명하는 문서"],
    ["소프트웨어 라이선스", "소프트웨어 사용 권한을 정의하는 법적 문서"],
    ["오픈소스(Open Source)", "소스 코드가 공개된 소프트웨어"],
    ["GPL(General Public License)", "가장 강력한 오픈소스 라이선스"],
    ["LGPL(Lesser General Public License)", "GPL보다 완화된 라이선스"],
    ["Apache 2.0 라이선스", "특허 조항이 포함된 오픈소스 라이선스"],
    ["MIT 라이선스", "가장 자유로운 오픈소스 라이선스"],
    ["BSD 라이선스", "변형이 있는 오픈소스 라이선스"],
    ["Mozilla Public License(MPL)", "파일 수준의 카피레프트 라이선스"],
    ["Creative Commons(CC)", "창작물을 위한 라이선스"],
    ["Eclipse Public License(EPL)", "Eclipse 재단의 라이선스"],
    ["Unlicense", "저작권을 포기하는 라이선스"],
    ["WTFPL", "매우 자유로운 라이선스"],
  ],
  17: [
    ["크로스 컴파일(Cross Compilation)", "다른 플랫폼용 코드를 컴파일하는 것"],
    ["네이티브 컴파일(Native Compilation)", "현재 플랫폼용 코드를 컴파일하는 것"],
    ["AOT(Ahead-of-Time) 컴파일", "실행 전에 미리 컴파일하는 방식"],
    ["JIT(Just-In-Time) 컴파일", "실행 시점에 컴파일하는 방식"],
    ["트레이스 기반 JIT", "자주 실행되는 경로를 컴파일하는 JIT"],
    ["메서드 기반 JIT", "메서드 단위로 컴파일하는 JIT"],
    ["적응형 최적화(Adaptive Optimization)", "실행 정보를 기반으로 동적 최적화"],
    ["프로파일 기반 최적화(PGO)", "프로파일 데이터를 활용한 최적화"],
    ["인트린직(Intrinsic) 함수", "컴파일러가 특별히 처리하는 내장 함수"],
    ["벡터화(Vectorization)", "스칼라 연산을 벡터 연산으로 변환하는 최적화"],
    ["자동 벡터화(Auto-vectorization)", "컴파일러가 자동으로 수행하는 벡터화"],
    ["루프 언롤링(Loop Unrolling)", "루프를 펼쳐 오버헤드를 줄이는 최적화"],
    ["루프 재롤링(Loop Rerolling)", "펼쳐진 루프를 다시 감는 변환"],
    ["루프 퓨전(Loop Fusion)", "인접한 루프를 하나로 합치는 최적화"],
    ["루프 피싱(Loop Fission)", "하나의 루프를 여러 개로 분할하는 최적화"],
    ["루프 교환(Loop Interchange)", "중첩 루프의 순서를 바꾸는 최적화"],
    ["루프 구문 분석(Loop Tiling)", "캐시 지역성을 위한 루프 변환"],
    ["루프 중심 변환(Loop Centric Transformations)", "루프 성능 최적화 변환들의 총칭"],
    ["if-변환(If-Conversion)", "조건문을 조건부 이동으로 변환하는 최적화"],
    ["조건부 이동(Conditional Move)", "분기 없이 조건을 처리하는 명령어"],
    ["술어 실행(Predicated Execution)", "조건에 따라 명령어를 실행하는 기법"],
    ["소프트웨어 파이프라이닝", "루프의 연산을 재배치하여 파이프라인 효율을 높이는 기법"],
    ["모듈로 스케줄링(Modulo Scheduling)", "소프트웨어 파이프라이닝을 위한 스케줄링"],
    ["레지스터 윈도잉(Register Windowing)", "함수 호출 시 레지스터를 효율적으로 관리하는 기법"],
    ["레지스터 할당(Register Allocation)", "변수를 레지스터에 배정하는 과정"],
    ["레지스터 할당 그래프 컬러링", "그래프 컬러링을 이용한 레지스터 할당"],
    ["린드-커큐트리 알고리즘", "그래프 컬러링 기반의 레지스터 할당 알고리즘"],
    ["페트로프 알고리즘(Linear Scan)", "선형 스캔 기반의 레지스터 할당"],
    ["함수 인라인(Function Inlining)", "함수 호출을 함수 본문으로 대체하는 최적화"],
    ["함수 클로닝(Function Cloning)", "함수의 특수화된 버전을 만드는 최적화"],
    ["함수 전문화(Function Specialization)", "특정 인자에 최적화된 함수를 생성하는 기법"],
    ["귀납 변수(Induction Variable)", "루프에서 일정하게 증가/감소하는 변수"],
    ["귀납 변수 제거", "귀납 변수를 다른 변수로 대체하는 최적화"],
    ["강도 감소(Strength Reduction)", "비싼 연산을 싼 연산으로 대체하는 최적화"],
    ["곱셈을 시프트로 변환", "정수 곱셈을 시프트 연산으로 대체하는 최적화"],
    ["나눗셈을 곱셈으로 변환", "정수 나눗셈을 곱셈으로 대체하는 최적화"],
    ["코드 호이스팅(Code Hoisting)", "루프 불변 코드를 루프 밖으로 이동하는 최적화"],
    ["코드 스킹(Code Sinking)", "코드를 늦게 실행되는 곳으로 이동하는 최적화"],
    ["역최적화(Deoptimization)", "최적화된 코드를 원래대로 되돌리는 과정"],
    ["온 스택 교체(On-Stack Replacement)", "실행 중인 메서드를 동적으로 대체하는 기술"],
    ["핫 스왑(Hot Swap)", "실행 중인 코드를 동적으로 교체하는 기술"],
    ["동적 재컴파일(Dynamic Recompilation)", "런타임에 코드를 다시 컴파일하는 기술"],
    ["바이너리 번역(Binary Translation)", "기계어 코드를 다른 기계어로 번역하는 기술"],
    ["정적 바이너리 번역", "실행 전에 이루어지는 바이너리 번역"],
    ["동적 바이너리 번역", "실행 중에 이루어지는 바이너리 번역"],
    ["QEMU", "오픈소스 에뮬레이터 및 가상화 도구"],
    ["RISC-V", "오픈소스 명령어 집합 아키텍처"],
    ["ARM 아키텍처", "ARM Holdings의 RISC 기반 CPU 아키텍처"],
    ["x86 아키텍처", "Intel의 CISC 기반 CPU 아키텍처"],
    ["MIPS 아키텍처", "RISC 기반 CPU 아키텍처"],
    ["Power 아키텍처", "IBM의 RISC 기반 CPU 아키텍처"],
    ["SPARC 아키텍처", "Sun Microsystems의 RISC 아키텍처"],
    ["IA-64(Itanium)", "Intel과 HP가 개발한 EPIC 아키텍처"],
    ["AMD64(64비트)", "AMD의 64비트 x86 확장"],
    ["AVX(Advanced Vector Extensions)", "Intel의 SIMD 명령어 집합"],
    ["SSE(Streaming SIMD Extensions)", "Intel의 SIMD 명령어 집합"],
    ["NEON", "ARM의 SIMD 명령어 집합"],
    ["MMX(MultiMedia eXtensions)", "Intel의 초기 SIMD 명령어 집합"],
    ["명령어 집합 확장", "기본 명령어 집합에 추가된 특수 명령어들"],
    ["BMI(Bit Manipulation Instructions)", "Intel의 비트 조작 명령어"],
    ["AES-NI", "AES 암호화 가속 명령어"],
    ["SHA-NI", "SHA 해시 가속 명령어"],
    ["가상화 명령어(VT-x/AMD-V)", "CPU의 하드웨어 가상화 지원 명령어"],
    ["Trusted Execution Technology(TXT)", "Intel의 신뢰 실행 기술"],
    ["Software Guard Extensions(SGX)", "Intel의 메모리 보호 기술"],
    ["메모리 보호 키(PKU)", "메모리 페이지 단위 접근 제어"],
    ["ASLR(Address Space Layout Randomization)", "주소 공간 배치 난수화"],
    ["DEP(Data Execution Prevention)", "데이터 실행 방지"],
    ["SMEP(Supervisor Mode Execution Prevention)", "슈퍼바이저 모드 실행 방지"],
    ["SMAP(Supervisor Mode Access Prevention)", "슈퍼바이저 모드 접근 방지"],
    ["KASLR(Kernel Address Space Layout Randomization)", "커널 주소 공간 배치 난수화"],
  ],
  18: [
    ["멀티캐스팅(Multicasting)", "분산 시스템에서 그룹 통신 방식"],
    ["순서화(Ordering)", "분산 시스템에서 메시지 순서 보장"],
    ["FIFO 순서", "같은 송신자의 메시지 순서를 보장하는 방식"],
    ["인과적 순서(Causal Order)", "인과 관계가 있는 메시지의 순서를 보장하는 방식"],
    ["전체 순서(Total Order)", "모든 메시지의 전체 순서를 보장하는 방식"],
    ["하이브리드 순서(Hybrid Order)", "여러 순서 방식을 혼합한 방식"],
    ["안정성(Stability)", "메시지가 더 이상 변경되지 않는 상태"],
    ["가비지 컬렉션(메시지)", "안정적인 메시지를 제거하는 과정"],
    ["분산 공유 메모리(DSM)", "분산 환경에서 공유 메모리를 제공하는 기술"],
    ["일관성 모델(Consistency Model)", "메모리 일관성을 정의하는 모델"],
    ["엄격한 일관성(Strict Consistency)", "가장 강력한 일관성 모델"],
    ["순차적 일관성(Sequential Consistency)", "모든 연산이 순서대로 보이는 모델"],
    ["인과적 일관성(Causal Consistency)", "인과 관계가 있는 연산의 순서를 보장하는 모델"],
    ["PRAM(Pipelined RAM) 일관성", "각 프로세서의 쓰기 순서만 보장하는 모델"],
    ["약한 일관성(Weak Consistency)", "동기화 지점에서만 일관성을 보장하는 모델"],
    ["릴리스 일관성(Release Consistency)", "획득과 해제로 동기화하는 모델"],
    ["진입 일관성(Entry Consistency)", "동기화 객체에 대한 일관성 모델"],
    ["분산 객체(Distributed Object)", "네트워크를 통해 접근하는 객체"],
    ["CORBA(Common Object Request Broker Architecture)", "분산 객체를 위한 미들웨어 표준"],
    ["DCOM(Distributed Component Object Model)", "Microsoft의 분산 객체 기술"],
    ["RMI(Remote Method Invocation)", "Java의 분산 객체 기술"],
    ["Java RMI", "Java의 원격 메서드 호출"],
    [".NET Remoting", "Microsoft의 분산 객체 기술"],
    ["Web Services", "웹 기반의 분산 서비스"],
    ["SOAP(Simple Object Access Protocol)", "XML 기반의 웹 서비스 프로토콜"],
    ["WSDL(Web Services Description Language)", "웹 서비스를 기술하는 XML 형식"],
    ["UDDI(Universal Description Discovery and Integration)", "웹 서비스 레지스트리"],
    ["RESTful 웹 서비스", "REST 원칙을 따르는 웹 서비스"],
    ["JSON API", "JSON을 사용하는 API"],
    ["OpenAPI(Swagger)", "REST API 명세 표준"],
    ["GraphQL", "쿼리 기반의 API 프로토콜"],
    ["웹 훅(Webhook)", "이벤트 기반의 HTTP 콜백"],
    ["서버 전송 이벤트(SSE)", "단방향 실시간 통신 기술"],
    ["웹소켓(WebSocket)", "양방향 실시간 통신 프로토콜"],
    ["Socket.IO", "웹소켓 라이브러리"],
    ["STOMP(Simple Text Oriented Messaging Protocol)", "메시징 프로토콜"],
    ["AMQP(Advanced Message Queuing Protocol)", "메시지 지향 미들웨어 프로토콜"],
    ["MQTT(Message Queuing Telemetry Transport)", "사물인터넷을 위한 경량 메시징 프로토콜"],
    ["ZeroMQ", "고성능 비동기 메시징 라이브러리"],
    ["분산 시스템의 장애", "분산 시스템에서 발생할 수 있는 다양한 오류"],
    ["크래시 장애(Crash Failure)", "서버가 중단되는 장애"],
    ["생략 장애(Omission Failure)", "응답을 보내지 않는 장애"],
    ["시간 장애(Timing Failure)", "시간 제약을 위반하는 장애"],
    ["응답 장애(Response Failure)", "잘못된 응답을 보내는 장애"],
    ["임의 장애(Arbitrary Failure)", "예측 불가능한 장애"],
    ["마스킹(Masking)", "장애를 감추는 기법"],
    ["재시도(Retry)", "실패한 연산을 다시 시도하는 기법"],
    ["타임아웃(Timeout)", "일정 시간 초과 시 실패 처리하는 기법"],
    ["폴트 내성(Fault Tolerance)", "장애에도 시스템이 작동하는 능력"],
    ["여분(Redundancy)", "장애 대비를 위한 추가 자원"],
    ["페일오버(Failover)", "장애 발생 시 예비 시스템으로 전환"],
    ["페일백(Failback)", "장애 복구 후 원래 시스템으로 복귀"],
    ["핸드오프(Handoff)", "작업을 다른 노드에 전달하는 과정"],
    ["체크포인트(Checkpoint)", "시스템 상태를 저장하는 지점"],
    ["로그 기반 복구(Log-based Recovery)", "로그를 이용한 장애 복구"],
    ["그룹 통신(Group Communication)", "그룹 내 노드 간 통신"],
    ["멤버십(Membership)", "그룹의 구성원 관리"],
    ["가십(Gossip)", "정보를 확산하는 프로토콜"],
    ["유질서(Atomic Broadcast)", "메시지를 원자적으로 전송하는 방식"],
    ["의사 결정(Consensus)", "여러 노드가 동일한 결정에 도달하는 문제"],
    ["합의(Agreement)", "노드들이 같은 값에 동의하는 문제"],
    ["체계적 장애(Byzantine Failure)", "악의적인 행동을 포함한 장애"],
    ["비잔틴 장애 허용(Byzantine Fault Tolerance)", "악의적인 노드가 있어도 합의에 도달하는 능력"],
  ],
  19: [
    ["스프라이트(Sprite)", "2D 그래픽스에서 사용되는 이미지 객체"],
    ["타일맵(Tilemap)", "타일 기반의 2D 맵 표현 방식"],
    ["스크롤링(Scrolling)", "화면을 이동시키는 기술"],
    ["평행 스크롤링(Parallax Scrolling)", "레이어별로 다른 속도로 스크롤하는 기술"],
    ["충돌 감지(Collision Detection)", "객체 간 충돌을 감지하는 기술"],
    ["AABB 충돌(Axis-Aligned Bounding Box)", "축 정렬 경계 상자 충돌 감지"],
    ["구체 충돌(Sphere Collision)", "구체 기반 충돌 감지"],
    ["폴리곤 충돌(Polygon Collision)", "다각형 기반 정밀 충돌 감지"],
    ["이펙트(Effect)", "시각적 특수 효과"],
    ["파티클 시스템(Particle System)", "다수의 작은 입자를 이용한 효과 시스템"],
    ["연기 효과(Smoke Effect)", "연기를 시뮬레이션하는 파티클 효과"],
    ["불 효과(Fire Effect)", "불을 시뮬레이션하는 파티클 효과"],
    ["폭발 효과(Explosion Effect)", "폭발을 시뮬레이션하는 효과"],
    ["물 시뮬레이션(Water Simulation)", "물의 움직임을 시뮬레이션"],
    ["천 시뮬레이션(Cloth Simulation)", "천의 움직임을 시뮬레이션"],
    ["연체 시뮬레이션(Soft Body)", "물체의 변형을 시뮬레이션"],
    ["강체 시뮬레이션(Rigid Body)", "단단한 물체의 물리 시뮬레이션"],
    ["물리 엔진(Physics Engine)", "물리 현상을 시뮬레이션하는 엔진"],
    ["Bullet Physics", "오픈소스 물리 엔진"],
    ["PhysX", "NVIDIA의 물리 엔진"],
    ["Havok", "상업용 물리 엔진"],
    ["Box2D", "2D 물리 엔진"],
    ["Chipmunk", "2D 물리 엔진"],
    ["중력(Gravity)", "만유인력을 시뮬레이션하는 힘"],
    ["마찰(Friction)", "물체 간 마찰력"],
    ["탄성(Elasticity)", "충돌 시 튕기는 성질"],
    ["운동량(Momentum)", "물체의 운동 상태를 나타내는 물리량"],
    ["힘(Force)", "물체의 운동 상태를 변화시키는 요인"],
    ["토크(Torque)", "회전력을 나타내는 물리량"],
    ["관성(Inertia)", "물체가 운동 상태를 유지하려는 성질"],
    ["질량(Mass)", "물체의 무게를 나타내는 물리량"],
    ["밀도(Density)", "단위 부피당 질량"],
    ["중심 질량(Center of Mass)", "물체의 질량 중심점"],
    ["경계 볼륨(Bounding Volume)", "충돌 감지를 위한 단순화된 볼륨"],
    ["경계 상자(Bounding Box)", "축 정렬 또는 객체 정렬의 경계 상자"],
    ["경계 구체(Bounding Sphere)", "구체 형태의 경계 볼륨"],
    ["OBB(Oriented Bounding Box)", "객체 방향을 따르는 경계 상자"],
    ["kd-트리(kd-Tree)", "공간 분할 트리"],
    ["BVH(Bounding Volume Hierarchy)", "경계 볼륨 계층 구조"],
    ["옥트리(Octree)", "3차원 공간 분할 트리"],
    ["BSP 트리(Binary Space Partitioning)", "이진 공간 분할 트리"],
    ["공간 분할(Spatial Partitioning)", "공간을 분할하여 효율성을 높이는 기법"],
    ["블렌딩(Blending)", "여러 이미지를 혼합하는 기술"],
    ["알파 블렌딩(Alpha Blending)", "투명도를 고려한 이미지 혼합"],
    ["가산 블렌딩(Additive Blending)", "색상을 더하는 블렌딩"],
    ["곱셈 블렌딩(Multiplicative Blending)", "색상을 곱하는 블렌딩"],
    ["마스킹(Masking)", "특정 영역만 표시하는 기술"],
    ["크로마 키(Chroma Key)", "특정 색상을 투명하게 만드는 기술"],
    ["래스터화(Rasterization)", "벡터 그래픽을 래스터 이미지로 변환"],
    ["앨리어싱(Aliasing)", "디지털 이미지에서 발생하는 계단 현상"],
    ["안티앨리어싱(Anti-aliasing)", "계단 현상을 줄이는 기술"],
    ["멀티샘플링 안티앨리어싱(MSAA)", "여러 위치를 샘플링하는 안티앨리어싱"],
    ["슈퍼샘플링 안티앨리어싱(SSAA)", "고해상도로 렌더링 후 축소하는 안티앨리어싱"],
    ["FXAA(Fast Approximate Anti-Aliasing)", "빠른 근사 안티앨리어싱"],
    ["SMAA(Subpixel Morphological Anti-Aliasing)", "서브픽셀 형태학적 안티앨리어싱"],
    ["TAA(Temporal Anti-Aliasing)", "이전 프레임 정보를 활용한 안티앨리어싱"],
    ["더블 버퍼링(Double Buffering)", "두 개의 버퍼로 화면 전환을 부드럽게 하는 기술"],
    ["트리플 버퍼링(Triple Buffering)", "세 개의 버퍼를 사용하는 기술"],
    ["수직 동기(VSync)", "화면 찢김을 방지하는 동기화"],
    ["G-Sync", "NVIDIA의 가변 주사율 기술"],
    ["FreeSync", "AMD의 가변 주사율 기술"],
    ["HDR(High Dynamic Range)", "넓은 명암비를 표현하는 기술"],
    ["톤 매핑(Tone Mapping)", "HDR을 SDR로 변환하는 과정"],
    ["감마 보정(Gamma Correction)", "모니터의 감마 특성을 보정하는 과정"],
    ["sRGB 색 공간", "표준 RGB 색 공간"],
    ["DCI-P3 색 공간", "영화 산업의 표준 색 공간"],
    ["Rec. 709", "HDTV의 색 공간 표준"],
    ["Rec. 2020", "UHDTV의 색 공간 표준"],
    ["어도비 RGB", "Adobe의 색 공간"],
    ["ProPhoto RGB", "Kodak의 색 공간"],
    ["색 심도(Color Depth)", "픽셀당 색상 정보의 비트 수"],
    ["8비트 색상", "채널당 8비트의 색상 표현"],
    ["10비트 색상", "채널당 10비트의 색상 표현"],
    ["12비트 색상", "채널당 12비트의 색상 표현"],
    ["HDR10", "10비트 HDR 표준"],
    ["Dolby Vision", "12비트 HDR 표준"],
    ["HLG(Hybrid Log-Gamma)", "방송용 HDR 표준"],
    ["모션 캡처(Motion Capture)", "실제 움직임을 디지털로 기록하는 기술"],
    ["광학식 모션 캡처", "카메라로 마커를 추적하는 방식"],
    ["관성식 모션 캡처", "센서로 움직임을 측정하는 방식"],
    ["페이셜 캡처(Facial Capture)", "얼굴 표정을 캡처하는 기술"],
    ["ARKit", "Apple의 증강 현실 프레임워크"],
    ["ARCore", "Google의 증강 현실 프레임워크"],
    ["OpenXR", "크로스 플랫폼 VR/AR 표준"],
    ["SteamVR", "Valve의 VR 플랫폼"],
    ["Oculus SDK", "Meta의 VR 개발 키트"],
  ],
  20: [
    ["이진 관계(Binary Relation)", "두 집합 간의 관계"],
    ["역관계(Inverse Relation)", "관계의 방향을 반대로 바꾼 관계"],
    ["합성 관계(Composition of Relations)", "두 관계를 순차적으로 적용한 관계"],
    ["반사 관계(Reflexive Relation)", "모든 원소가 자기 자신과 관계를 가지는 관계"],
    ["대칭 관계(Symmetric Relation)", "a가 b와 관계있으면 b도 a와 관계있는 관계"],
    ["반대칭 관계(Antisymmetric Relation)", "a가 b와 관계있고 b가 a와 관계있으면 a=b인 관계"],
    ["추이 관계(Transitive Relation)", "a가 b와 관계있고 b가 c와 관계있으면 a가 c와 관계있는 관계"],
    ["동치 관계(Equivalence Relation)", "반사적, 대칭적, 추이적 관계"],
    ["부분 순서(Partial Order)", "반사적, 반대칭적, 추이적 관계"],
    ["전순서(Total Order)", "모든 원소가 비교 가능한 부분 순서"],
    ["하세 도표(Hasse Diagram)", "부분 순서를 간략히 표현한 그래프"],
    ["극대 원소(Maximal Element)", "자신보다 큰 원소가 없는 원소"],
    ["극소 원소(Minimal Element)", "자신보다 작은 원소가 없는 원소"],
    ["최대 원소(Maximum Element)", "모든 원소보다 크거나 같은 원소"],
    ["최소 원소(Minimum Element)", "모든 원소보다 작거나 같은 원소"],
    ["상계(Upper Bound)", "어떤 집합의 모든 원소보다 크거나 같은 원소"],
    ["하계(Lower Bound)", "어떤 집합의 모든 원소보다 작거나 같은 원소"],
    ["최소 상계(Supremum)", "상계 중 가장 작은 원소"],
    ["최대 하계(Infimum)", "하계 중 가장 큰 원소"],
    ["격자(Lattice)", "모든 두 원소가 상계와 하계를 가지는 부분 순서 집합"],
    ["분배 격자(Distributive Lattice)", "분배 법칙을 만족하는 격자"],
    ["불 대수(Boolean Algebra)", "여집합이 정의된 분배 격자"],
    ["고전 논리(Classical Logic)", "전통적인 논리 체계"],
    ["직관 논리(Intuitionistic Logic)", "배중률을 인정하지 않는 논리 체계"],
    ["모달 논리(Modal Logic)", "가능성과 필연성을 다루는 논리"],
    ["시간 논리(Temporal Logic)", "시간의 개념을 포함하는 논리"],
    ["퍼지 논리(Fuzzy Logic)", "부분적 진리값을 허용하는 논리"],
    ["논리적 추론(Logical Reasoning)", "전제로부터 결론을 도출하는 과정"],
    ["연역적 추론(Deductive Reasoning)", "일반적인 원리에서 특정 결론을 도출"],
    ["귀납적 추론(Inductive Reasoning)", "관찰에서 일반적 원리를 도출"],
    ["귀추적 추론(Abductive Reasoning)", "가장 그럴듯한 설명을 찾는 추론"],
    ["건전성(Soundness)", "참인 전제에서 참인 결론이 도출되는 성질"],
    ["완전성(Completeness)", "모든 참인 명제가 증명 가능한 성질"],
    ["결정 가능성(Decidability)", "명제의 참/거짓을 결정할 수 있는 성질"],
    ["멱등법칙(Idempotent Law)", "같은 연산을 반복해도 결과가 같은 법칙"],
    ["흡수법칙(Absorption Law)", "논리 연산의 흡수 법칙"],
    ["부정 법칙(Negation Law)", "부정에 관한 논리 법칙"],
    ["쌍대 원리(Duality Principle)", "연산자를 교체해도 성질이 유지되는 원리"],
    ["쾨니히스베르크 다리 문제", "그래프 이론의 시작이 된 문제"],
    ["7개의 다리 문제", "쾨니히스베르크의 일곱 다리 문제"],
    ["오일러 트레일(Eulerian Trail)", "모든 간선을 한 번씩 지나는 경로"],
    ["오일러 서킷(Eulerian Circuit)", "모든 간선을 한 번씩 지나 시작점으로 돌아오는 경로"],
    ["오일러 그래프(Eulerian Graph)", "오일러 서킷이 존재하는 그래프"],
    ["해밀턴 경로(Hamiltonian Path)", "모든 정점을 한 번씩 지나는 경로"],
    ["해밀턴 그래프(Hamiltonian Graph)", "해밀턴 서킷이 존재하는 그래프"],
    ["완전 그래프(Complete Graph, Kn)", "모든 정점이 연결된 그래프"],
    ["정규 그래프(Regular Graph)", "모든 정점의 차수가 같은 그래프"],
    ["이분 그래프(Bipartite Graph)", "정점을 두 그룹으로 나눌 수 있는 그래프"],
    ["완전 이분 그래프(Complete Bipartite Graph, Kmn)", "모든 정점이 상대 그룹의 모든 정점과 연결된 이분 그래프"],
    ["평면 그래프(Planar Graph)", "간선이 교차하지 않게 그릴 수 있는 그래프"],
    ["비평면 그래프(Nonplanar Graph)", "간선이 반드시 교차하는 그래프"],
    ["K5(비평면 그래프)", "5개의 정점으로 이루어진 비평면 완전 그래프"],
    ["K33(비평면 그래프)", "3:3 완전 이분 비평면 그래프"],
    ["그래프의 차수(Degree)", "정점에 연결된 간선의 수"],
    ["차수 수열(Degree Sequence)", "그래프의 모든 정점 차수를 나열한 수열"],
    ["손잡이 정리(Handshaking Lemma)", "모든 정점 차수의 합은 간선 수의 2배"],
    ["그래프 동형(Graph Isomorphism)", "구조가 동일한 두 그래프"],
    ["동형 사상(Isomorphism)", "구조를 보존하는 일대일 대응"],
    ["그래프의 부속(Incidence)", "정점과 간선의 관계"],
    ["인접(Adjacency)", "정점과 정점 또는 간선과 간선의 관계"],
    ["인접 행렬(Adjacency Matrix)", "그래프의 인접 관계를 행렬로 표현"],
    ["부속 행렬(Incidence Matrix)", "그래프의 부속 관계를 행렬로 표현"],
    ["인접 리스트(Adjacency List)", "그래프의 인접 관계를 리스트로 표현"],
    ["그래프 색칠(Graph Coloring)", "그래프의 정점에 색을 칠하는 문제"],
    ["4색 정리(Four Color Theorem)", "모든 평면 그래프는 4색으로 칠할 수 있다는 정리"],
    ["그래프의 채색수(Chromatic Number)", "그래프를 색칠하는 데 필요한 최소 색의 수"],
    ["꼭짓점 덮개(Vertex Cover)", "모든 간선이 선택된 정점에 연결되도록 하는 정점 집합"],
    ["클릭(Clique)", "그래프에서 모든 정점이 서로 연결된 부분 그래프"],
    ["독립 집합(Independent Set)", "서로 인접하지 않은 정점들의 집합"],
    ["꼭짓점 연결도(Vertex Connectivity)", "그래프의 연결성을 나타내는 척도"],
    ["간선 연결도(Edge Connectivity)", "그래프의 간선 연결성 척도"],
    ["절단점(Cut Vertex)", "제거 시 그래프가 분리되는 정점"],
    ["절단간선(Cut Edge/Bridge)", "제거 시 그래프가 분리되는 간선"],
    ["이중 연결 그래프(Biconnected Graph)", "절단점이 없는 그래프"],
    ["강한 연결(Strongly Connected)", "방향 그래프에서 양방향 도달 가능"],
    ["약한 연결(Weakly Connected)", "방향을 무시했을 때 연결된 그래프"],
    ["방향 비순환 그래프(DAG)", "사이클이 없는 방향 그래프"],
  ],
};
async function main() {
  const existing = await new Promise(resolve => {
    http.get('http://192.168.0.3:8080/problem', res => {
      let b = ''; res.on('data', d => b += d);
      res.on('end', () => { try { resolve(JSON.parse(b).array.length); } catch(e) { resolve(0); } });
    });
  });
  console.log(`현재: ${existing}개`);
  let total = 0;
  for (const [catSN, terms] of Object.entries(data)) {
    let c = 0;
    for (const [name, def] of terms) {
      await cp(name, def, catSN); c++; total++;
      await cp(`${name}이란?`, `${name} 은/는 ${def}`, catSN); c++; total++;
      await cp(`${name} 설명`, def, catSN); c++; total++;
    }
    console.log(`  ${catSN}: ${terms.length}개 × 3 = ${c}개`);
  }
  const final = await new Promise(resolve => {
    http.get('http://192.168.0.3:8080/problem', res => {
      let b = ''; res.on('data', d => b += d);
      res.on('end', () => { try { resolve(JSON.parse(b).array.length); } catch(e) { resolve(0); } });
    });
  });
  console.log(`\n완료: 기존 ${existing}개 + 신규 ${total}개 = 총 ${final}개`);
}
main().catch(console.error);
