DROP TABLE PROBLEM;
DROP TABLE CATEGORY;
DROP TABLE PROBLEM_SET;
DROP TABLE USER;



CREATE TABLE USER
(
    `SN`            BIGINT UNSIGNED        NOT NULL    AUTO_INCREMENT, 
    `ID`            VARCHAR(45)    NOT NULL, 
    `PW`            VARCHAR(45)    NOT NULL, 
    `INTRODUCTION`  VARCHAR(45)    NULL, 
    PRIMARY KEY (SN),
    unique(ID)
);


CREATE TABLE PROBLEM_SET
(
    `SN`             BIGINT UNSIGNED            NOT NULL    AUTO_INCREMENT, 
    `NAME`           VARCHAR(45)        NOT NULL, 
    `OWNER`          BIGINT UNSIGNED    NOT NULL, 
    `TAG`            LONGTEXT           NULL, 
    `HIT`            INT                NOT NULL    DEFAULT 0, 
    `CREATED_DATE`   DATETIME           NOT NULL    DEFAULT NOW(), 
    `MODIFIED_DATE`  DATETIME           NOT NULL    DEFAULT NOW(), 
    PRIMARY KEY (SN)
);
ALTER TABLE PROBLEM_SET
    ADD CONSTRAINT FK_PROBLEM_SET_OWNER_USER_SN FOREIGN KEY (OWNER)
        REFERENCES USER (SN) ON DELETE RESTRICT ON UPDATE RESTRICT; 
        
CREATE TABLE CATEGORY
(
    `SN`           BIGINT UNSIGNED             NOT NULL    AUTO_INCREMENT, 
    `NAME`         VARCHAR(45)        NOT NULL, 
    `PROBLEM_SET`  BIGINT UNSIGNED    NOT NULL, 
    PRIMARY KEY (SN)
);

ALTER TABLE CATEGORY
    ADD CONSTRAINT FK_CATEGORY_PROBLEM_SET_PROBLEM_SET_SN FOREIGN KEY (PROBLEM_SET)
        REFERENCES PROBLEM_SET (SN) ON DELETE RESTRICT ON UPDATE RESTRICT;
        
        

CREATE TABLE PROBLEM
(
    `SN`        BIGINT UNSIGNED      NOT NULL    AUTO_INCREMENT, 
    `QUESTION`  LONGTEXT    NOT NULL, 
    `ANSWER`    LONGTEXT    NOT NULL, 
    `CATEGORY`  BIGINT UNSIGNED      NULL, 
    `HIT`       INT         NOT NULL    DEFAULT 0, 
    PRIMARY KEY (SN)
);

ALTER TABLE PROBLEM
    ADD CONSTRAINT FK_PROBLEM_CATEGORY_CATEGORY_SN FOREIGN KEY (CATEGORY)
        REFERENCES CATEGORY (SN) ON DELETE RESTRICT ON UPDATE RESTRICT;
